### ISSUE TITLE
Give LoadObj's istream overload a default material reader implementation

### ISSUE THREAD

**Issue by kavika13** [syoyo/tinyobjloader#100]
`LoadObj` has an overload that takes a `istream`, however it also takes a `MaterialReader* readMatFn` parameter that has no default value. There is an implementation provided in tinyobjloader for this class, but it expects a filename, and opens the `ifstream` itself.

It is simple enough for me to build my own implementation (copy and paste the version that takes a filename, and modify a couple simple lines), but I think it would be convenient to provide a `MaterialReader` implementation that takes an existing `istream`. It would also be convenient to make the default value `NULL`, the way that `LoadObjWithCallback` already does, since `LoadObj` already handles the null case.

My use case is that I have built some slightly complex loading logic to find and open a file stream, and I pass that stream into my resource loaders so they can do their job. This lets me centralize search paths logic, and allows me to abstract my stream sources so that I can do automated testing without touching the filesystem.

**Comment by syoyo** [comment]
`LoadObj` interface is a bit old and has a room for the improvement.

>  It would also be convenient to make the default value NULL

> My use case is that I have built some slightly complex loading logic to find and open a file stream, and I pass that stream into my resource loaders so they can do their job. This lets me centralize search paths logic, and allows me to abstract my stream sources so that I can do automated testing without touching the filesystem.

Interesting. Do you have a pseudo code of this? PR is also appreciated.

**Comment by kavika13** [comment]
That last paragraph is my own code, and wouldn't be generically useful in the context of this library. Just wanted to give a clear rationale for a fix to tinyobjloader.

Since you asked for pseudocode for that bit, I'll throw up some strawman executable pseudocode (python). My real thing is C++ and Lua, but this could theoretically exist too :)

    # in unit tests...
    import StringIO

    def test_obj_file_loader_works_at_all(self):
        test_obj_data = '... some vertices and junk'
        fake_obj_file = StringIO.StringIO(test_obj_data)
        mesh = ObjFileResouce.load(fake_obj_file)
        self.assertEqual(len(mesh.vertices), 45)

    # in generic resource loading code...
    function load_resource(resource_type, filename):
        paths_to_try = [
            'base_game_path/' + filename,
            'installed_mod_path/' + filename,
            'user_home_dir_mod_path/' + filename]

        for path in paths_to_try:
            if file.exists(path):
                file_stream = file.open(path)
                return resource_type.load(file_stream)

        raise 'could not find resource: ' + filename

> PR is also appreciated.

Check back in a few minutes.

**Comment by syoyo** [comment]
> That last paragraph is my own code, and wouldn't be generically useful in the context of this library

I see. Anyway thanks for pseudo code.

Also thanks for PR. I've merged it.
