### ISSUE TITLE
A shape is lost if obj ends with a 'usemtl'

### ISSUE THREAD

**Issue by gcorvala** [syoyo/tinyobjloader#104]
After this fix: https://github.com/syoyo/tinyobjloader/issues/68
If a file ends with usemtl, the last exportFaceGroupToShape (https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.h#L1340) returns false because the faceGroup is empty.

As a consequence, the last shape is lost.

**Comment by syoyo** [comment]
Thanks for the report. And now the issue has been fixed.
