### ISSUE TITLE
Example viewer vb variables

### ISSUE THREAD

**Issue by mmontag** [syoyo/tinyobjloader#108]
Hi, could I suggest different variable names for the GLuint `vb` member of `DrawObject` struct and the vector\<float\> `vb` vertex buffer in this example code? Particularly confusing around line 378:

https://github.com/syoyo/tinyobjloader/blob/master/examples/viewer/viewer.cc#L378

**Comment by syoyo** [comment]
You can use your favourite variable name and send a PR.

Perhaps `vector<float> vertex_buffer` and `GLuint vb_idx` would be nice?
