### ISSUE TITLE
.mtl file not found when .obj loaded from subdirectory

### ISSUE THREAD

**Issue by mmontag** [syoyo/tinyobjloader#109]
I have cube.obj and cube.mtl under a models/ folder.

`tinyobj::LoadObj(&attrib, &shapes, &materials, &err, "models/cube.obj");`

I see 

`WARN: Material file [ cube.mtl ] not found. Created a default material.` 

tiny_obj_loader is looking for cube.mtl in the executable working directory instead of the models folder. The material file should probably be loaded from the same path as the obj file.

**Comment by skurmedel** [comment]
Have you tried giving it an absolute basedir? For example "/mystuff/project1/models/". It is the next parameter after the filename and defaults to nothing. Another solution would be to wrap MaterialFileReader and pass that to the other LoadObj.

**Comment by syoyo** [comment]
Another option is use `mtl_basedir` 

https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.h#L304

> The material file should probably be loaded from the same path as the obj file.

You can send a PR to search .mtl file from the same directory of .obj file.

**Comment by syoyo** [comment]
example `viewer` now seeks .mtl file from a directory where .obj exist.

This sample code will help you.

https://github.com/syoyo/tinyobjloader/blob/master/examples/viewer/viewer.cc#L209

**Comment by mmontag** [comment]
👏
