### ISSUE TITLE
Voxelizer example Makefile and missing file

### ISSUE THREAD

**Issue by spasts** [syoyo/tinyobjloader#115]
It seems that the example Voxelize (https://github.com/syoyo/tinyobjloader/tree/master/examples/voxelize) is missing a file.

Looking at the define VOXELIZER_IMPLEMENTATION on github it seems that this file is coming from this lib https://github.com/karimnaaji/voxelizer.

Is it possible to add a Makefile and that missing file?

**Comment by syoyo** [comment]
Thanks for pointing out it. This is my fault that some files are not added to git repo.
