### ISSUE TITLE
Application crashed when I run it with /MTd

### ISSUE THREAD

**Issue by lhzqwe** [syoyo/tinyobjloader#116]
How can I do it if I want to use it as a static lib?

**Comment by syoyo** [comment]
Please post reproducing code.

**Comment by lhzqwe** [comment]
First, I clone your code from master.
![qq 20161220125611](https://cloud.githubusercontent.com/assets/18499665/21338726/bf679ec8-c6b3-11e6-8862-45461a8d90c8.png)
As my project is Win32, So I changed the header "tinyobj_loader_opt.h" like above.
Here is my main file.
[main.txt](https://github.com/syoyo/tinyobjloader/files/662805/main.txt)
When I run it with /MDd, it goes right.
But if I changed to /MTd, the application crashed:
![qq 20161220130403](https://cloud.githubusercontent.com/assets/18499665/21338839/d1a82084-c6b4-11e6-8a3b-fd998c19fca9.png)
It seems sizeClass out of access violation. Is there some problem with Italloc?

**Comment by syoyo** [comment]
`tinyobj_loader_opt.h` is experimental and it is not tested well on Windows platform.

Please use `tiny_obj_loader.h` if you don't need absolute parsing performance.

**Comment by syoyo** [comment]
I have fixed WIn32 build of `tinyobj_loader_opt.h` in the recent master, and tried to compile your code, but `/MTd` works well with `data/cornell_box.obj`.

Thus, it looks like your .obj file(`model/cabinet.ob`) is not supported well for tinyobj_opt or somewhat data is corrupted.

**Comment by syoyo** [comment]
Reopen the issue if you still have a problem(with attaching .obj)

**Comment by lhzqwe** [comment]
That's the .obj problem. &  Thank you so much.
