### ISSUE TITLE
Move TINYOBJLOADER_IMPLEMENTATION section of tiny_obj_loader.h

### ISSUE THREAD

**Issue by braddabug** [syoyo/tinyobjloader#122]
Right now the TINYOBJLOADER_IMPLEMENTATION section is inside the #ifndef TINY_OBJ_LOADER_H_ stuff, which is causing problems with my unity build setup (where I #include all my .cpp files in a single file and just build that one file). What happens is that a compilation unit contains TINY_OBJ_LOADER_H_ from where I'm #including tiny_obj_loader.h, then later in the same compilation unit I'm trying to add the TINYOBJLOADER_IMPLEMENTATION stuff, but because it sees the TINY_OBJ_LOADER_H_ from the earlier include everything gets ignored.

I propose moving TINYOBJLOADER_IMPLEMENTATION *after* the #ifndef TINY_OBJ_LOADER_H ... #endif section. That shouldn't cause any problems for anyone else doing it the regular way, but it will also let people like me do our unity build stuff. Sean Barrett's single file libraries work that way.

**Comment by syoyo** [comment]
Thank you for the detailed explanation.

> I propose moving TINYOBJLOADER_IMPLEMENTATION after the #ifndef TINY_OBJ_LOADER_H ... #endif section

This makes sense. I've fixed it in the recent commit.
