### ISSUE TITLE
double precision for scientific applications

### ISSUE THREAD

**Issue by noma** [syoyo/tinyobjloader#124]
I'm using tinyobjloader for a scientific code, where I work with double precision values.

For that I basically replaced every float with a real_t that can be compile time configured to either be float or double via some flag. I also adapted the CMakeLists.txt to create two libraries, one postfixed with '_double'. I've forked some time ago, so my branch is rather outdated. It can be found here:

https://github.com/noma/tinyobjloader

If that is some feature you deem useful for others, I would redo the changes for the current master branch and post a merge request.

**Comment by syoyo** [comment]
Super cool!

Double precision support is quite nice for HPC applications, and compile time `real_t` typedef approach is also handy and right way to switch the precision.

Could you please apply your changes to recent `master` and send us PR?
