### ISSUE TITLE
Wrong triangle number

### ISSUE THREAD

**Issue by E-BAO** [syoyo/tinyobjloader#127]
In file tinyobjloader/examples/viewer/viewer.cc  line 424
To calculate the number of the triangles, you do this:
 o.numTriangles = vb.size() / (3 + 3 + 3 + 2) * 3;
But I think it should be the number of vertexes / 3, that is: 
 o.numTriangles = vb.size() / (3 + 3 + 3 + 2) / 3;
It leads to a waste when rendering, because the vertex buffer is not that long.

**Comment by syoyo** [comment]
Oops, you are right.

Thank you for pointing out. Now its fixed!
