### ISSUE TITLE
The experimental code doesn't work for aarch64

### ISSUE THREAD

**Issue by qpoisson** [syoyo/tinyobjloader#129]
Try to use the loader in Android JNI code. 
However, I got error : unrecognized instruction mnemonic when compiling ltalloc.cc for aarch64.

**Comment by syoyo** [comment]
You can contribute by modifying ltalloc to run on aarc64, or remove ltalloc dependency.

**Comment by syoyo** [comment]
In recent `master`,  I have changed to use lfpAlloc https://github.com/ALSchwalm/lfpAlloc instead of ltalloc. 
At least it should now compile well on Android aarch64.
