### ISSUE TITLE
Experimental loader (tinyobj_loader_opt.h multi-threaded) fails on small number of face

### ISSUE THREAD

**Issue by orenouard** [syoyo/tinyobjloader#130]
Here is a simple exemple to reproduce it :

v -0.500000 -0.000000 0.500000
v 0.500000 -0.000000 0.500000
v -0.500000 0.000000 -0.500000
v 0.500000 0.000000 -0.500000
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 1.000000 0.000000
f 1/1/1 2/2/2 4/4/3 3/3/4

 Fails with both 1 or multiple threads :

 of threads = 8
total parsing time: 3.33952 ms
  line detection : 1.22226 ms
  alloc buf      : 0.021993 ms
  parse          : 1.16361 ms
  merge          : 0.924027 ms
  construct      : 0.000293 ms
  mtl load       : 4.80533e-312 ms
  of vertices = 12
  of normals = 12
   of texcoords = 8
  of face indices = 0
  of indices = 0
  of shapes = 0

 of threads = 1
total parsing time: 2.03837 ms
  line detection : 1.37827 ms
  alloc buf      : 0.015249 ms
  parse          : 0.226388 ms
  merge          : 0.273601 ms
  construct      : 0.000293 ms
  mtl load       : 4.09524e-312 ms
 of vertices = 12
  of normals = 12
 of texcoords = 8
  of face indices = 0
 of indices = 0
 of shapes = 0

[plane1.zip](https://github.com/syoyo/tinyobjloader/files/1133723/plane1.zip)

**Comment by orenouard** [comment]
Ok I think I found it, it was the last line always being omitted in the parsing for endlines and line_infos creation, as end index was using len-1 even though it's an open end index. ie should be auto end_idx = (std::min)((t + 1) * chunk_size, len; instead of end_idx = (std::min)((t + 1) * chunk_size, len-1)

**Comment by syoyo** [comment]
Thank you for finding an issue!

> auto end_idx = (std::min)((t + 1) * chunk_size, len

It looks this modification does not work. Instead, it would be better to switch to single-threaded parser when the size of input .obj is small. I will try to modify the experimental MT parser in that way.

**Comment by syoyo** [comment]
I think I have fixed the issue in this commit: https://github.com/syoyo/tinyobjloader/commit/8e7da8285275d41ebca3f9e747d5129a12b22d88 

At least now `plane1.obj` can be parsed correctly.
Could you please confirm the issue has been solved, @orenouard ?

**Comment by orenouard** [comment]
Yes I wasn't clear I had to change both lines 1304 and 1334, can confirm the issue is solved though (without the line 1304 mod it will be caught by the "extra span" logic at 1334)

**Comment by syoyo** [comment]
Thanks!
