### ISSUE TITLE
Python wrapper should return some kind of mapping from integer material ID to string material name

### ISSUE THREAD

**Issue by mikeroberts3000** [syoyo/tinyobjloader#131]
Hello there,

This obj loader looks great. As far as I can tell though, there there is a subtle design oversight in the Python wrapper.

For each face, the Python wrapper returns an integer material ID. The Python wrapper also returns a dictionary of materials (i.e., a mapping from string material names to various material properties). But there is no mapping from integer material IDs to string material names.

Suppose some face has a material_id of 1. I have no way of knowing which material properties this material_id refers to, because Python dictionaries are unordered and cannot be indexed with the material ID.

Cheers,
Mike

**Comment by syoyo** [comment]
Python binding was contributed by contributors and was incomplete and not maintained well. 

>  But there is no mapping from integer material IDs to string material names.

I see. we need a mapping of material ID and name pairs

Contribution is always welcome!

**Comment by syoyo** [comment]
@chrisliebert kindly contributed material <-> id pair dict support. This should fix the issue.
