### ISSUE TITLE
サンプルでのerror C4430

### ISSUE THREAD

**Issue by kaisereagle** [syoyo/tinyobjloader#137]
はじめまして
tinyobjloaderを使わせてもらおうと思い一度サンプルのviewerをビルドしようとしてプロジェクトを作成しましたが以下のエラーが出てきてしまいます

>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(94): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(94): error C2146: 構文エラー: ';' が、識別子 'MMVERSION' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(102): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(102): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(112): error C3646: 'ms': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(112): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(113): error C3646: 'sample': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(113): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(114): error C3646: 'cb': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(114): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(115): error C3646: 'ticks': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(115): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(120): error C3646: 'hour': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(120): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(121): error C3646: 'min': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(121): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(122): error C3646: 'sec': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(122): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(123): error C3646: 'frame': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(123): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(124): error C3646: 'fps': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(124): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(125): error C3646: 'dummy': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(125): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(127): error C3646: 'pad': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(127): error C2143: 構文エラー: ',' が '[' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(127): error C2143: 構文エラー: ')' が ';' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(127): error C2238: ';' の前に無効なトークンがあります。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(134): error C3646: 'songptrpos': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(134): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): error C2377: 'FAR': 再定義されています。typedef は他のどのシンボルでもオーバーロードできません
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(102): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(275): error C2065: 'HDRVR': 定義されていない識別子です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(275): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(297): error C2146: 構文エラー: ')' が、識別子 'DRVCALLBACK' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(297): error C2146: 構文エラー: ';' が、識別子 'DRVCALLBACK' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(297): error C2059: 構文エラー: ')'
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(297): error C2065: 'HDRVR': 定義されていない識別子です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(297): error C2146: 構文エラー: ')' が、識別子 'hdrvr' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(299): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(299): error C2146: 構文エラー: ';' が、識別子 'FAR' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(299): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(299): error C2086: 'int FAR': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(49): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(49): error C2146: 構文エラー: ';' が、識別子 'MCIERROR' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(58): error C2143: 構文エラー: ')' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(58): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(58): error C2371: 'CALLBACK': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(297): note: 'CALLBACK' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(58): error C2059: 構文エラー: ')'
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(58): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(65): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(65): error C2146: 構文エラー: ';' が、識別子 'MCIERROR' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(75): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(75): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(75): error C2146: 構文エラー: ';' が、識別子 'MCIERROR' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(90): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(90): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(90): error C2146: 構文エラー: ';' が、識別子 'MCIERROR' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(100): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(100): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(100): error C2146: 構文エラー: ';' が、識別子 'MCIERROR' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(115): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(115): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(115): error C2146: 構文エラー: ';' が、識別子 'MCIDEVICEID' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(122): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(122): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(122): error C2146: 構文エラー: ';' が、識別子 'MCIDEVICEID' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(134): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(134): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(134): error C2146: 構文エラー: ';' が、識別子 'MCIDEVICEID' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(142): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(142): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(142): error C2146: 構文エラー: ';' が、識別子 'MCIDEVICEID' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(155): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(155): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(155): error C2146: 構文エラー: ';' が、識別子 'BOOL' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(164): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(164): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(164): error C2146: 構文エラー: ';' が、識別子 'BOOL' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(186): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(186): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(186): error C2146: 構文エラー: ';' が、識別子 'BOOL' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(217): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(217): error C2086: 'int DECLSPEC_IMPORT': 再定義されました。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(64): note: 'DECLSPEC_IMPORT' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(217): error C2146: 構文エラー: ';' が、識別子 'BOOL' の前に必要です。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(517): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(517): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(518): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(518): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(518): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(525): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(525): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(527): error C3646: 'lpstrDeviceType': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(527): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(528): error C3646: 'lpstrElementName': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(528): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(529): error C3646: 'lpstrAlias': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(529): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(532): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(532): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(534): error C3646: 'lpstrDeviceType': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(534): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(535): error C3646: 'lpstrElementName': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(535): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(536): error C3646: 'lpstrAlias': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(536): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(562): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(562): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(565): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(565): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(565): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(570): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(570): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(572): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(572): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(572): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(577): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(577): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(578): error C3646: 'dwReturn': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(578): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(581): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(581): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(581): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(588): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(588): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(589): error C3646: 'lpstrReturn': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(589): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(593): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(593): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(594): error C3646: 'lpstrReturn': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(594): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(616): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(616): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(619): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(619): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(619): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(626): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(626): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(627): error C3646: 'lpstrReturn': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(627): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(633): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(633): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(634): error C3646: 'lpstrReturn': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(634): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(662): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(662): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(665): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(665): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(665): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(670): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(670): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(673): error C3646: 'hwndBreak': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(673): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(680): error C2143: 構文エラー: ';' が '*' の前にありません。
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(680): error C2371: 'FAR': 再定義されています。異なる基本型です。
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\mmsyscom.h(137): note: 'FAR' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(680): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(688): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(688): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(689): error C3646: 'lpfilename': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(689): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(692): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(692): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(693): error C3646: 'lpfilename': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(693): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(717): error C3646: 'dwCallback': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(717): error C4430: 型指定子がありません - int と仮定しました。メモ: C++ は int を既定値としてサポートしていません
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(718): error C3646: 'lpfilename': 不明なオーバーライド指定子です
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mciapi.h(718): fatal error C1003: プログラム内のエラーが 100 個を超えました。コンパイルは中断されます。
1

環境は
VS2008
VS2010
VS2012
VS2013
VS2015
VS2017

ビルドはpremake-5.0.0-alpha12-windowsとcmake-2.8.12.2-win32-x86にてプロジェクトを作成しましたが
すべてのvisualstudioにて上記エラーが起こります
またインクルードバージョンは
glew-2.1.0
GLFW 3.3
を使っております。
上記エラーはdirectX系にてよくインクルード先にて失敗した時出るようですがなにか他に設定する必要はありますでしょうか？

**Comment by syoyo** [comment]
Please don't post issue in Japanese.

**Comment by kaisereagle** [comment]
sory I'm japanese
error  issue was 
#include <mmsystem.h>
#include <windows.h>
#ifdef __cplusplus
↓
#include <windows.h>
#include <mmsystem.h>
#ifdef __cplusplus

ok
