### ISSUE TITLE
Groups not separated as different shapes

### ISSUE THREAD

**Issue by sunweilun** [syoyo/tinyobjloader#138]
Dear 'tinyobjloader' authors,

Thanks for your contribution. 'tinyobjloader' is a very useful tool for me. Recently, I had some issues with 'tinyobjloader' ignoring the 'g' tag. I hope we can fix it to further improve 'tinyobjloader'. Below is what I have found:

When 'g' immediately follows 'usemtl' in the obj file, the loader ignores the 'g' tag and does not create a new shape.

Related lines (1621-1626) in tiny_obj_loader.h:

      // flush previous face group.
      bool ret = exportFaceGroupToShape(&shape, faceGroup, tags, material, name,
                                        triangulate);
      if (ret) {
        shapes->push_back(shape);
      }

Here, it is possible that all faces in the buffer have been dumped because of the 'usemtl' tag above the 'g' tag at this point. This way, 'exportFaceGroupToShape' will return 0 and a new shape for the 'g' tag will not be created. What I think we really want is that we create a new shape as long as the previous shape is not empty. 

Suggested change:

      // flush previous face group.
      exportFaceGroupToShape(&shape, faceGroup, tags, material, name,
                                        triangulate);
      
      if (shape.mesh.indices.size()) {
        shapes->push_back(shape);
      }

Let me know whether this makes sense.

Thanks!

**Comment by syoyo** [comment]
Thank you for finding an issue.

> Suggested change:

This looks nice.

Do you have small test .obj/.mtl to reproduce this issue?
Before fixing the issue, I would like to add test dataset as a regression.

**Comment by sunweilun** [comment]
Attached. It is a cube with 2 groups. (One is the front face, the other has
all the other faces.)

The loader will load it as a single shape. With the fix, it loads the obj
as 2 separate shapes.

Thanks for taking care of this!

**Comment by syoyo** [comment]
> Attached. It is a cube with 2 groups

Hmm... It looks file attachments are missing in your comment.

**Comment by sunweilun** [comment]
Did it work this time?

**Comment by syoyo** [comment]
> Did it work this time?

Unfortunately no.

Did you attach files through github web UI?

**Comment by sunweilun** [comment]
[test.zip](https://github.com/syoyo/tinyobjloader/files/1293358/test.zip)

This time? Sorry, I was using emails.

**Comment by syoyo** [comment]
Thanks!

I did quick fix and pushed as  `group-fix` branch https://github.com/syoyo/tinyobjloader/tree/group-fix

But I'm not sure this change is safe.
IIRC, the may may affects with previous issue: https://github.com/syoyo/tinyobjloader/issues/104

Thus after some tests and code reviews, the change will be merged into `master`

**Comment by sunweilun** [comment]
Sweet! Thanks!

**Comment by syoyo** [comment]
It looks it does not produce any side effects, thus merged into `master`
