### ISSUE TITLE
Incorrect .obj loading

### ISSUE THREAD

**Issue by matanui159** [syoyo/tinyobjloader#140]
Using the sample OBJ:
```
mtllib test.mtl

v -0.5 -0.5 0
v 0.5 -0.5 0
v 0.5 0.5 0
v -0.5 0.5 0

vt 0 0 0
vt 1 0 0
vt 1 1 0
vt 0 1 0

vn 0 0 -1

usemtl main
f 0/0/0 1/1/0 3/3/0
f 1/1/0 3/3/0 2/2/0
```

with the sample MTL:
```
newmtl main
Kd 1 1 1
```

and the sample code:
```c++
 ...
tinyobj::attrib_t attrib;
std::vector<tinyobj::shape_t> shapes;
std::vector<tinyobj::material_t> materials;
std::string error;
tinyobj::LoadObj(&attrib, &shapes, &materials, &error, argv[2]);
if (!error.empty()) throw error;
 ...
std::cout << "VERTICES:" << std::endl;
for (float x : attrib.vertices) {
	std::cout << x << std::endl;
}
std::cout << std::endl;

std::cout << "NORMALS:" << std::endl;
for (float x : attrib.normals) {
	std::cout << x << std::endl;
}
std::cout << std::endl;

std::cout << "TEXCOORDS:" << std::endl;
for (float x : attrib.texcoords) {
	std::cout << x << std::endl;
}
std::cout << std::endl;

std::cout << "FACES:" << std::endl;
for (tinyobj::shape_t& x : shapes) {
	for (unsigned char y : x.mesh.num_face_vertices) {
		std::cout << (int)y << std::endl;
	}
}
std::cout << std::endl;

std::cout << "INDICES:" << std::endl;
for (tinyobj::shape_t& x : shapes) {
	for (tinyobj::index_t y : x.mesh.indices) {
		std::cout << y.vertex_index << "/" << y.texcoord_index << "/" << y.normal_index << std::endl;
	}
}
std::cout << std::endl;
 ...
```

the following is produced:
```
VERTICES:
-0.5
-0.5
0
0.5
-0.5
0
0.5
0.5
0
-0.5
0.5
0

NORMALS:
0
0
-1

TEXCOORDS:
0
0
1
0
1
1
0
1

FACES:
3
3

INDICES:
0/0/0
0/0/0
2/2/0
0/0/0
2/2/0
1/1/0
```

where the indices are incorrect. The same occurs when disabling triangulation. I've looked through previous issues but couldn't find anything. I am using release v1.0.6.

**Comment by syoyo** [comment]
.obj data is wrong.

> f 0/0/0 1/1/0 3/3/0

`f` value should start with 1. 

http://www.fileformat.info/format/wavefrontobj/egff.htm

Negative value is allowed(for relative indexing), but `0` is not allowed.
You cannot load this .obj in another application for example MeshLab.

I may consider to print an error when `0` appears in `f` line.

**Comment by matanui159** [comment]
Its funny because I just realized that a second ago and was about to comment about my mistake only to find that you have already pointed it out 😄.

Sorry for bothering you.

**Comment by syoyo** [comment]
FYI, I have added zero-value check for `f' line in this commit: https://github.com/syoyo/tinyobjloader/commit/75a4bd1d35f489808a3e4dc52d0f9121823fe5f4

**Comment by syoyo** [comment]
And thank your for reporting an issue!
