### ISSUE TITLE
[TODO] [Extension] Support parsing vertex color

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyobjloader#144]
vertex color is not in .obj format but it would be nice to have such a feature through extension.

https://blender.stackexchange.com/questions/31997/how-can-i-get-vertex-painted-obj-files-to-import-into-blender

**Comment by anirudt** [comment]
+Add support for returning texture map filename as a string?

**Comment by syoyo** [comment]
Please don't post comments unrelated to the issue.

**Comment by syoyo** [comment]
Implemented in this commit: https://github.com/syoyo/tinyobjloader/commit/88ad575f6247a215bda2a8938bc0f6e41d113ea4

<img width="581" alt="screen shot 2017-10-13 at 1 56 30" src="https://user-images.githubusercontent.com/18676/31509035-f5dad952-afba-11e7-9667-c8116dfbae43.png">
