### ISSUE TITLE
Hi.... requesting some help

### ISSUE THREAD

**Issue by bjadamson** [syoyo/tinyobjloader#147]
Hi, I've been working at this issue for a few days, hoping to get some help from an expect.

I posted my question to SO... if that's not OK I can take some time to rewerite it for github. Thanks!
https://stackoverflow.com/questions/46760955/trouble-using-tinyobj-to-load-an-obj-file-confused-about-indices

**Comment by syoyo** [comment]
I guess you got an answer at SO.

`http://syoyo.github.io/tinyobjloader/` is quite old so I have updated the site to sync with https://github.com/syoyo/tinyobjloader
