### ISSUE TITLE
Triangulate doesn't appear to work on concave polygons.

### ISSUE THREAD

**Issue by raspofabs** [syoyo/tinyobjloader#150]
Hi, I was just importing your library into my project, and I was trying to use Kenney's 3d road tile assets, and noticed some odd z fighting. I have triangulate turned on, and it seems that triangulate is not checking to make sure the generated triangles only cover the area of the original polygon.

(Kenney includes a script to quadify assets, and running that seems to have fixed the issue, when looking at what the script does, it seems to use blender to convert to triangles, then to quads, so I suspect that Blender is triangulating better somehow.)

**Comment by raspofabs** [comment]
Here's the object that cought my attention 

[KenneyRoadTIle.zip](https://github.com/syoyo/tinyobjloader/files/1463958/KenneyRoadTIle.zip)

**Comment by syoyo** [comment]
Ah, triangulation algorithm currently being implemented is very simple one and does not support for concave polygons.

We need to implement more and better triangulation algorithm e.g. 

https://www.gamedev.net/articles/programming/graphics/polygon-triangulation-r3334/

**Comment by syoyo** [comment]
One candidate would be use https://github.com/mapbox/earcut.hpp

**Comment by raspofabs** [comment]
I'm going to have a go at fixing it myself. It doesn't look too hard to implement.

**Comment by raspofabs** [comment]
#151 Sorry, but writing the triangulation code was getting very verbose working without a vector type, so to write it I had to break the API. I suggest you merely use my pull request as a reference, rather than accept the merge, unless you're willing to start adding types to the attribute section.

**Comment by raspofabs** [comment]
I used a bad algorithm for the point in polygon test in that pull-request. I don't know when I will get to doing it, but it would be better to use the PNPOLY algorithm. https://wrf.ecse.rpi.edu//Research/Short_Notes/pnpoly.html as it looks like it should be possible to make it work without adding the vertex types, so could go in as a mainline pull-request instead of an API version bump.

If I get a chance to do it, I will submit a PR (this time, maybe I will be able to get it to run the tests as I won't be changing the API ;)

**Comment by syoyo** [comment]
> it would be better to use the PNPOLY algorithm. 

Good!

Your this PR #150 has been merged into `devel`, and its still ok to change API in this `devel` branch, so choices are:

1) Create a PR against `master`(no API/data structure modification) for current mainline release
2) Create a PR against `devel`(Do API/data structure modification, do whatever you want(e.g. you can discard your #150 PR))) for next release. 

I haven't yet decided when to release `devel` as `master`(v2.0.0), but it would be around spring 2018.

**Comment by syoyo** [comment]
> Create a PR against master(no API/data structure modification) for current mainline release
