### ISSUE TITLE
Seems like a memory leak?

### ISSUE THREAD

**Issue by ogrex** [syoyo/tinyobjloader#153]
I tried iterating loading the same file with lfpalloc multi-thread version without creating new data. It seems everytime I load it, memory is increased by around 10MB.
Then I changed back to lt::allocator version and memory increased only slightly by around 0.2MB each time.
Have you ever encountered such problem?

**Comment by syoyo** [comment]
I think `lfpalloc` pre-allocates some amount of memory for efficient multi-threaded memory allocation, thus this would not be an issue of memory leak.

For checking a memory leak, you can compile your program with ASAN(AddressSanitizer) https://github.com/google/sanitizers/wiki/AddressSanitizer

**Comment by ogrex** [comment]
pre-allocation should not be a problem if followed by free action afterwards. I checked by ASAN but nothing reported with lfpalloc.  
However, I still can not explain, for example, why running following code would increase the memory each time in iteration after first time execution. Since the arguments should be reset each time in parse() function
for(int i=0;i<10;++i){
parse(&attrib,&shape,&materials,&err,buf,len);
}

**Comment by syoyo** [comment]
If you have macOS, you can use `Instruments` tool to find where memory allocations happens.

https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/Instrument-Allocations.html

**Comment by syoyo** [comment]
Close the issue since there is no reproducable test code.

**Comment by n8vm** [comment]
For what it's worth, I seem to be able to reproduce this memory leak reported by @ogrex. By repeatedly calling parseObj, memory continues to rise. Most memory seems to be consumed by these "lfpAlloc::Node<fpAlloc::Chunk<>>" objects.

This is what a heap profile looks like after calling parseOBJ 100 times, and then freeing any loaded meshes
![image](https://user-images.githubusercontent.com/13104331/95640335-97cb9200-0a59-11eb-89ce-ba55029c1d98.png)
