### ISSUE TITLE
open bounty test

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyobjloader#157]
For testing Status Open Bounty

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8ceed0c1801719953f63ab4274d59c667542cff13ff1e14f441fd33c851a5e35](https://etherscan.io/tx/0x8ceed0c1801719953f63ab4274d59c667542cff13ff1e14f441fd33c851a5e35)
