### ISSUE TITLE
open bounty test 2

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyobjloader#158]
open bounty test 2

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf4725fe748a234d9f14baf4781a51d38634ad352799117931a633fef08a46108](https://etherscan.io/tx/0xf4725fe748a234d9f14baf4781a51d38634ad352799117931a633fef08a46108)

**Comment by syoyo** [comment]
Got it!
