### ISSUE TITLE
Assertion failure due to comparing an unsigned int with a signed int

### ISSUE THREAD

**Issue by gopalss** [syoyo/tinyobjloader#161]
I am using this code in my OpenGL project in Visual Studio 2017, C++. I tried the code for the following model in obj format:
                 https://grabcad.com/library/classic-dining-room-set-2-1
On my first attempt, there was assertion failure at the following code segment in the file viewer.cc:
        if (attrib.texcoords.size() > 0) {
            assert(attrib.texcoords.size() > 2 * idx0.texcoord_index + 1);

At the time of failure, idx0.texcoord_index was actually -1. Still the assertion failed because attrib.texcoords.size()  is an unsigned int. When comparing an unsigned int with a signed int, the comparison operator converts the signed int to unsigned int. When -1 is converted to an unsigned int, it becomes a large value. That is why the assertion failed.

 I propose the following fix:

       // Need to convert the unsigned int to signed int in order to compare with signed int.
      // Because, comparing an unsigned int with -1 will convert -1 to an unsigned int, which is huge.
      int texcoordsSize = (int)attrib.texcoords.size();
      if (texcoordsSize > 0 && idx0.texcoord_index >= 0 &&
             idx1.texcoord_index >= 0 && idx2.texcoord_index >= 0) {
                     assert(texcoordsSize > 2 * idx0.texcoord_index + 1);

With this fix, the code worked and imported that model.

**Comment by syoyo** [comment]
`-1` means coordinate index is not set in `f` line.

It looks .obj has an mixture of `f` line with texcoord and `f` line without texcoord index.
https://github.com/syoyo/tinyobjloader/issues/61

We may be better to check validity(negative value check) for each face element, not adding more assertions.

Also, could you please create minimal reproducable .obj file?

**Comment by gopalss** [comment]
You are right - the .obj has an mixture of f line with texcoord and f line without texcoord index. 

As per the specification, when you are using a series of triplets of an element, you must be consistent in the way you reference the vertex data. For example, it is illegal to give texture coordinates for some vertices, but not all. The following is an example of an illegal statement.
    f 1/1/1 2/2/2 3//3 4//4

As per my understanding, the above condition is for any one element (face). Different elements can have different combinations.  

Given below is a simple reproducible example, in which, all faces except the last face has texture coordinates. The last face does not have them. This example will encounter the assertion failure. After my proposed fix, the code works. All but the last face display the texture and the last face is drawn with plain color. Note that, the example requires an image file named cube.png for it to work. You can try any image in that name.

# cube.obj
#

o cube
mtllib cube.mtl

v -0.500000 -0.500000 0.500000
v 0.500000 -0.500000 0.500000
v -0.500000 0.500000 0.500000
v 0.500000 0.500000 0.500000
v -0.500000 0.500000 -0.500000
v 0.500000 0.500000 -0.500000
v -0.500000 -0.500000 -0.500000
v 0.500000 -0.500000 -0.500000

vt 0.000000 0.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000

g cube
usemtl cube
s 1
f 1/1 2/2 3/3
f 3/3 2/2 4/4
s 2
f 3/1 4/2 5/3
f 5/3 4/2 6/4
s 3
f 5/4 6/3 7/2
f 7/2 6/3 8/1
s 4
f 7/1 8/2 1/3
f 1/3 8/2 2/4
s 5
f 2/1 8/2 4/3
f 4/3 8/2 6/4
s 6
f 7/1 1/2 5/3
f 5 1 3

**Comment by gopalss** [comment]
I closed the issue by mistake.

**Comment by syoyo** [comment]
>As per the specification, when you are using a series of triplets of an element, you must be consistent in the way you reference the vertex data. For example, it is illegal to give texture coordinates for some vertices, but not all. The following is an example of an illegal statement.
f 1/1/1 2/2/2 3//3 4//4

Thank you. We'll have an choice to report such illegal statement as an error, or leave it as is(i.e. index have -1).
Probably we are better to introduce a flag for controlling parsing level(e.g. `TINYOBJ_ALLOW_ILLEGAL_FACE_LINE`)

**Comment by gopalss** [comment]
I want to make sure that I have communicated correctly. The simple example, cube.obj, given in my previous comment is a valid file as per the specification. Still, the current viewer.cc code fails because of the reported assertion failure. So, the code needs to be fixed to handle this valid case.

**Comment by syoyo** [comment]
> The simple example, cube.obj, given in my previous comment is a valid file as per the specification. Still, the current viewer.cc code fails because of the reported assertion failure

Ah, I see. I'll fix `viewer` example soon.

**Comment by syoyo** [comment]
I have fixed an issue and added above `cube.obj` to `models` directory for regression:  

https://github.com/syoyo/tinyobjloader/commit/12bf4165be5bf23c6fb2b1205aa2940f1f22751f#diff-6641c20f04ce477154272e4f0dd709e3R335

I have also considered the situation when normal index is missing for a face.
