### ISSUE TITLE
Hellishly large linker error messages

### ISSUE THREAD

**Issue by WarpspeedSCP** [syoyo/tinyobjloader#164]
Here's the gist for the error messages I got- https://gist.github.com/WarpspeedSCP/cd05471c3df50aeb220068e58026d8e2

I defined `TINYOBJLOADER_IMPLEMENTATION` before including `tiny_obj_loader.h`, and hit compile only to get hit by a wall of linker errors. Any fixes?

**Comment by syoyo** [comment]
`TINYOBJLOADER_IMPLEMENTATION` should be defined only in **ONE** .cpp/.cc

It looks you are defining it both VulkanFnLoaders.cc and main.cc

**Comment by WarpspeedSCP** [comment]
I have it defined in a common header file, which has those multi include guards as well.

**Comment by syoyo** [comment]
You must not define `TINYOBJLOADER_IMPLEMENTATION` in header file unless the header file is only included in one compilation unit.

**Comment by WarpspeedSCP** [comment]
Thank you,, and sorry.
