### ISSUE TITLE
use double compile error

### ISSUE THREAD

**Issue by ibtaylor** [syoyo/tinyobjloader#167]
when compiling with `-DTINYOBJLOADER_USE_DOUBLE=ON`, the following line fails to compile
https://github.com/syoyo/tinyobjloader/blob/b85714b4cf15f51e928d62e043014056e95e0629/tiny_obj_loader.h#L1129
```
error: cannot convert ‘tinyobj::real_t* {aka double*}’ to ‘float*’ for argument ‘2’ to ‘int tinyobj::pnpoly(int, float*, float*, float, float)’
```

**Comment by syoyo** [comment]
Oops, double precision is not supported for `pnpoly`(triangulation) function at the moment.
