### ISSUE TITLE
Multiple definition error

### ISSUE THREAD

**Issue by JackalopeGit** [syoyo/tinyobjloader#171]
![image](https://user-images.githubusercontent.com/33356711/38104015-a98d24d8-3390-11e8-979d-753c51978bd4.png)
cmake include:
```
include_directories(${CMAKE_SOURCE_DIR}/extra/TinyObjLoader)
link_directories(${CMAKE_SOURCE_DIR}/extra/TinyObjLoader)
```
TinyObjLoader is a directory with repository-clone

**Comment by JackalopeGit** [comment]
All works, only if move TINYOBJLOADER_IMPLEMENTATION code to cpp file.

**Comment by syoyo** [comment]
This is described in README and comments in the header file  > only if move TINYOBJLOADER_IMPLEMENTATION code to cpp file.

```
#define TINYOBJLOADER_IMPLEMENTATION // define this in only *one* .cc
#include "tiny_obj_loader.h"
```
