### ISSUE TITLE
Support for line elements?

### ISSUE THREAD

**Issue by clehmann-geo** [syoyo/tinyobjloader#173]
Hello,

I just realized that tinyobjloader seems to skip polylines defined in .obj files. Would it be possible to add support for them? Their definition in the .obj file is simple:

l v1 v2 v3 v4 v5 v6 ...

with v1...vi indicating the vertices of the polyline.
Thanks in advance for answer!

**Comment by syoyo** [comment]
Polyline is not yet implemented in TinyObjLoader.

You can contribute!

**Comment by clehmann-geo** [comment]
Okay, thanks, I will try to!
