### ISSUE TITLE
MTL file in same directory cannot be loaded

### ISSUE THREAD

**Issue by mlimper** [syoyo/tinyobjloader#177]
Hi @silverweed, Hi @syoyo !

I just updated tinyobj for my application, and there seems to be a problem:

On Windows, if the .mtl file is in the same directory and simply referenced as, say "myMTLFile.mtl" from within the OBJ, the current version fails to load it. There was a recent change via a PR: https://github.com/syoyo/tinyobjloader/pull/176

I suppose this is what broke it for this particular case - for the example mentioned above I get a warning from tinyOBI saying "WARN: Material file [ \myMTLFile.mtl ] not found.". I am not sure what would be the correct way to fix this (without breaking what @silverweed fixed in https://github.com/syoyo/tinyobjloader/pull/176, for example). For now I added a workaround changing the following (line 1747)

```
if (baseDir[baseDir.length() - 1] != dirsep)
      baseDir += dirsep;
```

to

```
if (!baseDir.empty() && baseDir[baseDir.length() - 1] != dirsep)
      baseDir += dirsep;
```

This worked for me, but, again, not sure if this is a good final fix.

Thanks & keep up the great work!

**Comment by silverweed** [comment]
Uh, apparently I totally overlooked that case, thanks for catching it. It looks a good fix to me: it's short and simple, and I can't think of additional corner cases where the result is wrong.

The alternative would be asserting that `mtl_basedir != ""` somewhere before that, but that looks much more painful and error-prone to me.

**Comment by mlimper** [comment]
OK, thanks for the quick reply!

Do you want to do a PR to continue with fixing this? Or should I?

**Comment by syoyo** [comment]
Yes, PR appreciated.

@mlimper  I don't have an access to Windows platform for a while, so please confirm this unit test case  https://github.com/syoyo/tinyobjloader/blob/master/tests/tester.cc#L771 fails on your side, then PR fixes it.
