### ISSUE TITLE
Problems with mixed triangle and quad meshes

### ISSUE THREAD

**Issue by vcosta** [syoyo/tinyobjloader#18]
Hello,
Looking at the code I expected it to flatten out mixed triangle and quad meshes into triangle meshes. However trying to read such data, as per the usage section of the main project page, results in a garbled mess. As for a file that displays this behaviour:
http://www.sci.utah.edu/~wald/animrep/fairy/fairy.obj.tgz

e.g. f000.obj.

**Comment by syoyo** [comment]
n-gon face(no triangulation) is now supported in recent `master`. Please try it.
