### ISSUE TITLE
Memory Leak in pyLoadObj

### ISSUE THREAD

**Issue by mathue** [syoyo/tinyobjloader#188]
In the Python function tinyobjloader.LoadObj or the C-Function pyLoadObj must be a memory leak. The memory is not free'd after the mesh is loaded. Therefore, if several meshes are loaded and the corresponding python variables were deleted or overwritten, the meshes still remain in the memory.

I created a pull request where I fixed these leaks in
https://github.com/syoyo/tinyobjloader/compare/master...mathue:patch-1

Best regards
Martin.

**Comment by syoyo** [comment]
Thank you for finding a memory leak issue and corresponding PR.
I have merged PR, thus now this issue should be ready to close.

**Comment by mathue** [comment]
You are welcome. I took me almost one day to find it ;-).
