### ISSUE TITLE
Can you make a minor release?

### ISSUE THREAD

**Issue by jasjuang** [syoyo/tinyobjloader#197]
Can you make a minor release? It's mainly for the integration into [vcpkg](https://github.com/Microsoft/vcpkg). Thanks!

**Comment by syoyo** [comment]
How to adapt for vcpkg? Just bumping version is enough?

**Comment by jasjuang** [comment]
Yes just bumping version will be good enough. Thanks!

**Comment by syoyo** [comment]
I have tagged v1.4.1(current v1.4 + some bug fix) https://github.com/syoyo/tinyobjloader/releases/tag/v1.4.1

**Comment by jasjuang** [comment]
Thanks!
