### ISSUE TITLE
I want to implement splitting an obj file into multiple obj files

### ISSUE THREAD

**Issue by simonasdmd** [syoyo/tinyobjloader#198]
Hi~
I want to implement splitting an obj file into multiple obj files. Can I use this? If you can give me some ideas.
Grateful.

**Comment by syoyo** [comment]
You can split obj file after reading .obj according to various criteria. For example

* per object
* per material
* for each specific number of vertices(e.g. 65536)

PR of example program is always welcome!

**Comment by simonasdmd** [comment]
Is there any relevant code to refer to? It is time-consuming to encounter this problem. I am also learning about obj related knowledge at the same time. If I can get the code or information I can quote, I can speed up my speed. Your help makes me very happy, thank you again.

**Comment by syoyo** [comment]
Please study wavefront .obj format and C++ firstly.
