### ISSUE TITLE
Add support for lines and points

### ISSUE THREAD

**Issue by xelatihy** [syoyo/tinyobjloader#199]
Tinyobj now supports only faces 'f' elements. It would be helpful to also support lines 'l' and points 'p' elements. If this were added only to the callback interface, the change could be made in a backward compatible manner.

**Comment by syoyo** [comment]
Line is already supported in recent `master`.

>  // version 1.2.1 : Added initial support for line('l') primitive(PR #178)

points(`p`) could be implemented in similar fashion. PR is welcome!

**Comment by xelatihy** [comment]
I saw that, but it seems that lines do not have texture coordinates or "normal", right?

**Comment by xelatihy** [comment]
Furthermore, lines are handles are pairs, but in reality they are polylines. They should be handled exactly line 'f' faces. Points too. And should be supported by the SAX parser. I ca take a crack at it and test it on my files if you want.

**Comment by syoyo** [comment]
http://paulbourke.net/dataformats/obj/

```
l  v1/vt1   v2/vt2   v3/vt3 . . .

    Polygonal geometry statement.

    Specifies a line and its vertex reference numbers. You can
    optionally include the texture vertex reference numbers. Although
    lines cannot be shaded or rendered, they are used by other Advanced
    Visualizer programs.

    The reference numbers for the vertices and texture vertices must be
    separated by a slash (/). There is no space between the number and
    the slash.

    v is a reference number for a vertex on the line. A minimum of two
    vertex numbers are required. There is no limit on the maximum.
    Positive values indicate absolute vertex numbers. Negative values
    indicate relative vertex numbers.

    vt is an optional argument.

    vt is the reference number for a texture vertex in the line
    element. It must always follow the first slash.
```

According to the spec, `l` is composed of vertices(polylines), not pairs of line segments. It could have texture coordinates but normal is not considered.

**Comment by xelatihy** [comment]
For the polylines, it is what I tried to say above. In tinyobj they seem to be handled as pairs. 

I added normals as convenience in my parser since "it won't hurt" but helps porting other data to OBJ (like cyhair or glTF). It is similar to the extension tinyobj has for vertex colors. 

As far as I can tell, lines can be handled like faces in tinyobj. Points would be handled identically since they are lists of points. If you are ok with it, I can take a crack at it and pull request it.

**Comment by syoyo** [comment]
> I added normals as convenience in my parser since "it won't hurt"

Yes, it is ok to support `v/vt/vn` triple style for `l` primitive(also for `p`?) as an tinyobj extension.
  
> pull request it.

Yeah! PR is much appreciated. It is ok to deprecate the current line segment version for line(`path_t`).

**Comment by xelatihy** [comment]
I was reviewing the code and noticed that tiny_obj does not error in the case of failed parsing of float/ints. That is perfectly fine but in my code I use strict errors since I got bitten in the past by  corrupt files that loaded by contained bad data. This cannot be easily fixed without changing the behaviour significantly. So I might still do this but not soon since adopting tiny_obj would require me the change error handling in my code quite a bit.

**Comment by syoyo** [comment]
lines and points are now supported 
 in recent `master` : https://github.com/syoyo/tinyobjloader/commit/87b906c64831dfc744a72287f9dc64b3a31f7407
