### ISSUE TITLE
Add extension for cameras and envmaps

### ISSUE THREAD

**Issue by xelatihy** [syoyo/tinyobjloader#200]
In my OBJ reader, I have a trivial way to save cameras and environment maps. It would be great to also have this in tinyobj. If there is interests, I can detail how I did it to make sure the files remained backward compatible.

**Comment by syoyo** [comment]
.obj is for geometry description format and there is no (defacto) standard to describe camera and envmap in .obj. Personally I recommend to provide your own `scene description` file something like 

https://github.com/lighttransport/nanort/blob/master/examples/gui/config.json

Other possible direction are define camera parameters in the comment, or define empty object for camera and envmap, assign .mtl and describe camera parameters and envmap parameters in .mtl, e.g.

```
# .obj

usemtl MTL

o Camera
usemtl camera
o Envmap
usemtl envmap
```

**Comment by xelatihy** [comment]
I simply use a third file .objx to stick all extensions. This way it does not interfere with any editing in other programs and can be copy pasted where one wants. I have a solution now, but to get it more used it would be good to have it in tinyobj. Ideas?

**Comment by syoyo** [comment]
Please file an issue with concrete proposal and ideas.
