### ISSUE TITLE
Support parsing leading decimal dot for minified obj files

### ISSUE THREAD

**Issue by stfx** [syoyo/tinyobjloader#201]
I recently tried to reduce the file size of my game and came across a tool to minify obj files:
https://compress-or-die.com/obj

One used method is to remove redundant information from decimal numbers by for example changing `-0.730000` to `-.73`.

Unfortunately tinyobjloader does not support parsing decimals with a leading decimal dot such as `.73` or `-.73` so it would be cool if this could be supported if it's not too much work.

**Comment by syoyo** [comment]
Parsing floating point value is all handled in `tryParseDouble`

https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.h#L567

It should be rather easy to adding support for parsing `.73` by tweaking this function. PR is always weldome!
