### ISSUE TITLE
Error on submodule update

### ISSUE THREAD

**Issue by TheLavaBlock** [syoyo/tinyobjloader#203]
I use it as submodule and have this error on update:

`fatal: no submodule mapping found in .gitmodules for path 'pybind11/tools/clang'
Failed to recurse into submodule path 'ext/tinyobjloader'`

How to fix this?

Do I have to add 

`../../wjakob/clang-cindex-python3`

to my project? I don't need python. 

I am using:

`git submodule update --recursive --remote`

Thanks in advance

**Comment by syoyo** [comment]
pybind11 submodule dependency is introduced recently to tinyobjloader(towards v2.0.0 release), but  this is optional. tinyobjloader does not require pybind11 by default(no python binding). So one possible solution is not updating tinyobjloader with `--recursive` option.

Better solution would be rebuild .gitmodules of your repo by removing/re-adding `tinyobjloader` submodule.

https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule

**Comment by TheLavaBlock** [comment]
Thanks for your quick reply. I prefer the first solution and removed `--recursive`.

**Comment by syoyo** [comment]
@TheLavaBlock 😎
