### ISSUE TITLE
Conan integration

### ISSUE THREAD

**Issue by jovobe** [syoyo/tinyobjloader#206]
Hi,

I just stumbled upon your library and I'm going to use it for my current project. As I am using [conan](https://conan.io/) to manage my dependencies I wanted to ask if you are planning to release a conan package of it in near future.

Best regards
Johan M.

**Comment by syoyo** [comment]
tinyobjloader is a single header library. You can just copy `tiny_obj_loader.h` file to your project. 

So I don't think its valuable to host tinyobjloader on conan. Contribution is welcome though.

**Comment by jovobe** [comment]
I know that but I value the advantages of a dependency manager over just copying external files into my project. I'm glad to here that you welcome contributions! If I find some time I will try to create a conan package for tinyobjloader.

**Comment by flostellbrink** [comment]
Hi!

I was also looking to include tinyobjloader via conan.
My [pull request to conan-center-index](https://github.com/conan-io/conan-center-index/pull/58) has been merged yesterday.
The package is now available in the [conan-center repository](https://bintray.com/conan/conan-center/tinyobjloader%3A_).

This is part of their early access program, but should work already.

**Comment by syoyo** [comment]
Awesome!

@flostellbrink Is there any source code modification required in tinyobjloader repo itself? if not, we can add a procedure of conan based tinyobjloader installation in README.md

**Comment by flostellbrink** [comment]
@syoyo Glad you like it.

This uses the source straight from the releases of the tinyobjloader repo.
It only injects a couple cmake parameters and cleans up the output for packaging.

I can do a quick write up of the procedure later today.
