### ISSUE TITLE
Materials are not loaded from obj dir with default reader config

### ISSUE THREAD

**Issue by giomatfois62** [syoyo/tinyobjloader#208]
Hey, i noticed that with the default ObjReaderConfig object passed to the ObjReader class materials files are not looked into the obj file directory, instead the path "./" is used, and if we try to load a model from a directory different than the application directory (for example load a model from file "../models/mymodel/mymode.obj") no materials are found obviously.

I patched the header making the default mtl_search_path empty in the default config and adding a control in the LoadObj function to build the directory path from the obj filename (simply iterating the string backward until a separator is found).

If you think this should be the intended behaviour I could make a pull request.
Anyway awesome job with this library, i really like it.

**Comment by syoyo** [comment]
Oh, I see >  instead the path "./" is used

> If you think this should be the intended behaviour I could make a pull request.

Yeah! PR is much welcome!(i.e. default behavior is try to seek `.mtl` file in the same directory where `.obj` file exists)

**Comment by theNded** [comment]
@giomatfois62 Is this done? Otherwise I will make a PR. Thanks!

**Comment by giomatfois62** [comment]
Yes it is! sorry for not coming back to you.
Thanks for your work on this
