### ISSUE TITLE
Some commit after f37fed3 breaks LoadObj

### ISSUE THREAD

**Issue by jasjuang** [syoyo/tinyobjloader#211]
On the latest master if I run the below minimal code,

```
  std::vector<double> vert_pos;
  std::vector<int> tri_ind;
  std::string obj_file = "/home/ubuntu/vertexmesh.obj";

  tinyobj::attrib_t attrib;
  std::vector<tinyobj::shape_t> shapes;
  std::vector<tinyobj::material_t> materials;

  std::string warn;
  std::string err;

  tinyobj::LoadObj(
          &attrib, &shapes, &materials, &warn, &err, obj_file.c_str());

  for (float vertice : attrib.vertices)
  {
    vert_pos.emplace_back(static_cast<double>(vertice));
  }

  for (auto &shape : shapes)
  {
    for (auto &indice : shape.mesh.indices)
    {
      tri_ind.emplace_back(indice.vertex_index);
    }
  }
```

I get error

```
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

vertexmesh.obj is a minimal obj like this
```
#vcount 4
#fcount 2
v 0 0 0
v 1 0 0
v 1 1 0
v 0 1 0
f 1 2 3
f 3 4 1
```

If I revert back to https://github.com/syoyo/tinyobjloader/commit/f37fed32f3eb0912cc10a970f78774cd98598ef6, everything works like usual.

I am on Ubuntu 18.04, GCC 7.

**Comment by syoyo** [comment]
I couldn't reproduce the issue.

It looks its a problem of your environment(e.g. runtime app uses old tinyobjloader .so) or a bug in gcc 7.

If you still face an issue, please post a minimal reproducable source code(and Makefile)

**Comment by jasjuang** [comment]
Weird enough if I delete the build folder and create a new one and then build, the error is gone.

**Comment by syoyo** [comment]
> Weird enough if I delete the build folder and create a new one and then build, the error is gone.

If you are using cmake to build tinyobjloader, this is a usual situation. I think there was some old setting in cmake cache. As you did, cleaning `build` directory and build from a scratch is the right solution.
