### ISSUE TITLE
Using 1.0.X tinyOBJLoader in GlslViewer

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [syoyo/tinyobjloader#218]
Hi @syoyo! I just edit https://github.com/patriciogonzalezvivo/glslViewer to use the latest tinyOBJLoader version and works like a charm. Thanks so much

**Comment by syoyo** [comment]
Cool! 

Added a link to glslViewer in RADME.md in this commit: https://github.com/syoyo/tinyobjloader/commit/0c4abeb2660e1006a767a0cbecdc9a1341b2de89

**Comment by patriciogonzalezvivo** [comment]
Thanks!
