### ISSUE TITLE
Using 1.0.X of tinyobjloader in rayrender

### ISSUE THREAD

**Issue by tylermorganwall** [syoyo/tinyobjloader#219]
Hi @syoyo! I have implemented support for obj files using tinyobjloader in my raytracer for R, rayrender:

www.rayrender.net
www.github.com/tylermorganwall/rayrender

Everything works great! Thanks you.

**Comment by syoyo** [comment]
Super awesome!

Added a link! > https://github.com/syoyo/tinyobjloader/commit/c0575ad1c7c476ea3dd8b010cf448bee779199b8
