### ISSUE TITLE
A few lines can be deleted in tinyobjloader.h

### ISSUE THREAD

**Issue by erich666** [syoyo/tinyobjloader#222]
Sorry, I should submit a pull request, but that'd take awhile for such a simple fix.

See https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.h#L862

Lines 862 and 865 can be deleted, since 

    if (!leading_decimal_dots) {

is already done just above, at line 854.

**Comment by syoyo** [comment]
> Lines 862 and 865 can be deleted

Thanks! removed these lines.
