### ISSUE TITLE
If material path is set, the loader ignores it.

### ISSUE THREAD

**Issue by marovira** [syoyo/tinyobjloader#223]
In `ObjReader::ParseFromFile` line 2887, there's a check to see if the material path is set. If it isn't then the root directory from the OBJ file itself is set as the material path. However, if the material path is set in the `ObjReaderConfig` object, then the string `mtl_search_path` is not set to anything and materials aren't loaded. This is a straight-forward fix by simply adding:

```c++
if (config.mtl_search_path.empty()) {
  // ...
} else {
  mtl_search_path = config.mtl_search_path;
}
```
I can make a pull request if required.

**Comment by syoyo** [comment]
Oh! thank you for pointing out the issue.

Now `mtl_search-path` is correctly set.
