### ISSUE TITLE
obj_sticher erro

### ISSUE THREAD

**Issue by simonasdmd** [syoyo/tinyobjloader#234]
I executed "obj_sticher. Exe" But there are some mistakes. 
The generated MTL file is empty. And obj file has texture coordinates but no corresponding texture "usemtl".
my test data:
[test.zip](https://github.com/syoyo/tinyobjloader/files/3813168/test.zip)

**Comment by syoyo** [comment]
Probably you are failed to find .mtl. Please add mtl search path in `LoadObj`, or run obj_sticher in .obj folder for example:

```
../bin/native/Release/obj_sticher 01.obj 02.obj combined.obj
```
