### ISSUE TITLE
Using 1.0.X of tinyobjloader in liblava

### ISSUE THREAD

**Issue by TheLavaBlock** [syoyo/tinyobjloader#236]
Hi, **liblava** is using tinyobjloader. Thank you for your great work!

[liblava](https://git.io/liblava) - A modern C++ and easy-to-use framework for the Vulkan API. [MIT]

**Comment by syoyo** [comment]
Super awesome! Added! > https://github.com/syoyo/tinyobjloader/commit/e0beb00b42fb8360e1cda8f63a8f954d05ef6a86
