### ISSUE TITLE
Calculate the normal of triangle face

### ISSUE THREAD

**Issue by simonasdmd** [syoyo/tinyobjloader#237]
hi.
Some of the obj files I get have no normals. Can I provide normals when exporting obj.
my data:
[yuan.zip](https://github.com/syoyo/tinyobjloader/files/3823550/yuan.zip)

**Comment by syoyo** [comment]
You need to calculate normals in your way. 

For example, you can calculate geometric normal like this:
  
https://github.com/syoyo/tinyobjloader/blob/master/examples/viewer/viewer.cc#L542
