### ISSUE TITLE
Potential bug in python binding shapes[0].mesh.numpy_indices()

### ISSUE THREAD

**Issue by KoykL** [syoyo/tinyobjloader#242]
Is this a bug (in python/bindings.cc):
`
.def("numpy_indices", [] (mesh_t &instance) {
        auto ret = py::array_t<int>(instance.indices.size() * 3);
}
`
Should it be `
auto ret = py::array_t<int>(instance.indices.size());
` ? 

I guess numpy_indices should return an array of same size as instance.indices, which has the same size as mesh.indices.

Thank you so much for your help!

**Comment by syoyo** [comment]
index is composed of 3 ints. so the code is correct.

I've added a detailed comment in https://github.com/syoyo/tinyobjloader/commit/bf3987441dea8d3a9edab43c554790c9349179e0.
