### ISSUE TITLE
Accessing material_ids in python binding

### ISSUE THREAD

**Issue by KoykL** [syoyo/tinyobjloader#243]
For some applications, it would be nice to know the material_ids for faces. Would it be possible to add access to material_ids in python binding?

e.g. In bindings.cc
`
py::class_<mesh_t>(tobj_module, "mesh_t")  
    .def(py::init<>())  
    .def_readonly("material_ids", &mesh_t::material_ids);  
`

**Comment by syoyo** [comment]
Yes, you can add such accessor to access to material property. Python binding is work-in-progress, so PR is appreciated!

**Comment by KoykL** [comment]
Thank you. I will do that when I have time.
