### ISSUE TITLE
usemtl doesn't parse string correctly

### ISSUE THREAD

**Issue by bensch128** [syoyo/tinyobjloader#246]
Hi, 
   I discovered a problem with the usemtl parsing when there's whitespace before or after the material string name.
Example .OBJ:
.....
usemtl  1 
.....
Example .MTL:
.....
newmtl 1 
.....

This was easy to solve by using the parseString() function instead of the stringstream approach.
Thanks!
Ben

[tinyobjloader.patch.txt](https://github.com/syoyo/tinyobjloader/files/3899404/tinyobjloader.patch.txt)

**Comment by bensch128** [comment]
I guess that I should open a PR but hopefully this patch is simple enough...

**Comment by syoyo** [comment]
Thanks! Fixed!

Also added a regression test : https://github.com/syoyo/tinyobjloader/blob/master/tests/tester.cc#L1255
