### ISSUE TITLE
how to get index array

### ISSUE THREAD

**Issue by tanpuer** [syoyo/tinyobjloader#247]
I am using tinyobjloader to build a simple 3DViewer Android application. I can render the classic teapot right now. But when using tinyobjloader, I don't know how to get index array to create index buffer. Can anyone give me some hint?

**Comment by syoyo** [comment]
https://github.com/syoyo/tinyobjloader/blob/master/examples/viewer/viewer.cc

**Comment by tanpuer** [comment]
> https://github.com/syoyo/tinyobjloader/blob/master/examples/viewer/viewer.cc

Thanks ! But I haven't get the point. I use opengles 3.0, can you explain how to get the indices array.
