### ISSUE TITLE
"texres" texture option is included in file name

### ISSUE THREAD

**Issue by MauricioVives** [syoyo/tinyobjloader#248]
When a MTL file has the "texres" texture option, the parsed file name includes it. For example:

`map_Kd -texres 512 textures\foo.jpg`

The file name in the material is parsed as:

`-texres 512 textures\foo.jpg` when it should be simply `textures\foo.jpg`

The problem is near the comment `// Assume texture filename` in the code, as it used to work with the currently disabled parsing code at that location.

**Comment by syoyo** [comment]
Oh, parsing `-texres` was not implemented.

Now implemented in `master` and parsing `texres` should work well.

**Comment by MauricioVives** [comment]
I tested it and that works, thanks for the quick turnaround!
