### ISSUE TITLE
Export cmake package

### ISSUE THREAD

**Issue by onionhammer** [syoyo/tinyobjloader#25]
http://www.cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

> libraries, but also tools that could be useful as a build-utility, such as documentation generators, wrapper generators, etc.) should provide at a minimum a <name>Config.cmake or a <lower-name>-config.cmake file. This file can then be used by the find_package() command in config-mode to provide information about include-directories, libraries and their dependencies, required compile-flags or locations of executables.

**Comment by syoyo** [comment]
PR please?
