### ISSUE TITLE
Load without duplicated vertices.

### ISSUE THREAD

**Issue by Makogan** [syoyo/tinyobjloader#252]
I have a cube obj (8 vertices) that I am loding using this library. 

I parse the data this way:

```
    for (const auto& shape : shapes)
    {
        for (const auto& index : shape.mesh.indices)
            /*Do stuff*/
    }
```

However even though the original obj only has 8 vertices, I am getting 36.

**Comment by syoyo** [comment]
https://github.com/syoyo/tinyobjloader/blob/eba1fc037e89a593f50d670621c0dbf9882ec78d/models/cube.obj#L15

Cube has 6 faces x 3 vtx per face x 2 faces = 36 vertices when triangulated.
