### ISSUE TITLE
Linux par parseFloat3 and parseFloat2 bug

### ISSUE THREAD

**Issue by kmkolasinski** [syoyo/tinyobjloader#28]
Hi, 
I had a problem with your OBJ loader on linux Ubuntu. Using your version of parseFloat3 and parseFloat2 functions the parsed values of vertices, normals and UV were wrong. I do know where was exactly the problem but if I replaced in parseFloat3 (same in parseFloat2):
  x = parseFloat(token);
  y = parseFloat(token);
  z = parseFloat(token);

with:
    std::stringstream ss;
    ss << token;
    ss >> x;
    ss >> y;
    ss >> z;

this solved my problem. I know that std::stringstream is slower than your implementation but it works, thats fine for me. I did't have any problem on Windows only on linux. I'm going to use tinyobjloader in my project: http://awesomebump.besaba.com/
Best regards,
Krzysztof Kolasinski

**Comment by syoyo** [comment]
Hello kmkolasinski

Do you have any .obj to reproduce your problem?

I am running on Ubuntu and at least get expect result with `cornell_box.obj`.

BTW, AB is super cool!

**Comment by kmkolasinski** [comment]
Hi,
Maybe this is because I'm building your library with Qt. I simply added .c
.h files directly to the project. Example file I have tried is in
attachement.

Best. Feel free to add AB to your project list. I will use your library for
sure :)


2015-02-15 15:19 GMT+01:00 Syoyo Fujita <notifications@github.com>:

> Hello kmkolasinski
>
> Do you have any .obj to reproduce your problem?
>
> I am running on Ubuntu and at least get expect result with cornell_box.obj
> .
>
> BTW, AB is super cool!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syoyo/tinyobjloader/issues/28#issuecomment-74419056>.
>



-- 
Pozdrawiam,
Krzysztof Kolasiński

**Comment by syoyo** [comment]
Hello, where can I find an attachment?

**Comment by kmkolasinski** [comment]
Hi, I wrote the answer via gmail, I forgot that github does not support attachments. Here is the file: http://speedy.sh/phuMe/SmoothedCube.zip
I will able answer next week.

**Comment by syoyo** [comment]
Great! Will investigate it.

**Comment by syoyo** [comment]
![smoothcube](https://cloud.githubusercontent.com/assets/18676/6266886/18fa0396-b882-11e4-9586-a38bf3a3e4a1.png)

It can render well using mallie https://github.com/lighttransport/mallie (which uses tinyobjloader).

And the problem would be locale setting in conjunction with Qt.

https://github.com/lighttransport/mallie

Can you try to put setlocale(LC_NUMERIC,"en_US"); before calling tinyobjloader function?

Write our own numeric parser will be a good issue for an enhancement of tinyobjloader. Contribution is welcome!

**Comment by skurmedel** [comment]
Can't you just temporarily set the locale to something else when parsing? I could write a parser if that is not a good solution though.

**Comment by syoyo** [comment]
>  I could write a parser

Cool! Replacing `atof()` with custom parser is far better than adding locale workaround.

**Comment by skurmedel** [comment]
atof() supports a number of stuff that doesn't seem to be kosher in a .obj, for example +/- NAN. Is it common with .obj-files that do? The standard is pretty badly written in that it doesn't actually state what format numbers are supposed to have, it only gives examples and they are all just decimal.

**Comment by kmkolasinski** [comment]
Hi, I have returned to your orginal code with atof function and suddenly the error disapeared ... very strange - I think this is because Qt sometimes requires to rebuild the  whole project in order to link all changes done in project. Maybe this is the reason why I had previously errors during model reading.
Did anyone send you a report with same problem as me?
Sorry for bothering you. 
K,

**Comment by syoyo** [comment]
> NAN 

Sometimes I see NaN string something like:

```
v nan, nan, nan 
```

Thus writing a custom parser needs some trick.

> Did anyone send you a report with same problem as me?

No, at this time, but I'd like to avoid the situation that atof() behaviour is affected by locale setting.

**Comment by kmkolasinski** [comment]
"Sometimes I see NaN string something like"
Ok, thank you I had similar problem like you, so I will not risk with atof and return to the std::stringstream function.

**Comment by skurmedel** [comment]
I'm working on a parser to replace the important parts of atof's functionality, I'll add support for "+NAN" and "-NAN" too then.

Here's the current grammar (without NAN-support):
```ebnf
sign    = "+" | "-" ;
END     = ? anything not in digit ?
digit   = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
integer = [sign] , digit , {digit} ;
decimal = integer , ["." , {digit}] ;
float   = ( decimal , END ) | ( decimal , ("E" | "e") , integer , END ) ;
```
Stuff like:

    +3.1417e+2  -0.E-3  1.0324  -1.41   11e2   1234

will supported.

**Comment by syoyo** [comment]
Cool!

And, on VisualStudio, it may print `1.#NAN`.

http://www.johndcook.com/blog/ieee_exceptions_in_cpp/

**Comment by syoyo** [comment]
@kmkolasinski, can you try this fix kindly provided by @skurmedel  ?

https://github.com/syoyo/tinyobjloader/commit/79af31df5a83045bde8a7a47369b930f260116cf

**Comment by kmkolasinski** [comment]
Hi, 
I've tried few models with AwesomeBump and It perfectly worked.

**Comment by syoyo** [comment]
Super cool! > @kmkolasinski

**Comment by syoyo** [comment]
Close. We can open new issue when we need precise support for `nan`.
