### ISSUE TITLE
map_Kd etc

### ISSUE THREAD

**Issue by slitazcn** [syoyo/tinyobjloader#30]
why not use strnicmp,there always get nothing

**Comment by syoyo** [comment]
Do you have any test case?

**Comment by slitazcn** [comment]
yes,I use test.cc test some obj files,and there always is map_kd not map_Kd,so,I must do more work to get the texture name from the unknown parameter,my obj file is use assimpviewer export,I think maybe can ignore the letter case,thanks for your comment,sorry about my poor english

**Comment by syoyo** [comment]
I see.

According to the spec, `map_Kd` is the right answer, 

http://paulbourke.net/dataformats/mtl/

Although the spec does not define the spec is case sensitive or not.

**Comment by slitazcn** [comment]
yes...i still like no case sensitive~~~then will be more flexible,THX,I just deal with the unknown_parameter,thanks again for reply
