### ISSUE TITLE
Bad allocation Error rungholt scene

### ISSUE THREAD

**Issue by NoxMortem** [syoyo/tinyobjloader#31]
The blog post on http://swarminglogic.com/jotting/2013_10_gamedev01 lead me to this nice little library. Sadly for the rungholt scene i get an bad allocation during loading the rungholt scene from http://graphics.cs.williams.edu/data/meshes.xml

    // group name
    if (token[0] == 'g' && isSpace((token[1]))) {

      // flush previous face group.
      bool ret = exportFaceGroupToShape(shape, vertexCache, v, vn, vt,
                                        faceGroup, material, name, true);
      if (ret) {
        shapes.push_back(shape);
      }

      shape = shape_t();/// bad allocation

It might be very important to note that I get a bad allocation error with the assimp model loader library for this scene as well, so it could be very much a problem on my side, but I would appreciate any guidance to fix/solve the problem :)

Edit: OK with the release built and in release mode the library does not seem to fail (/Ox). Still it takes like 5 minutes to load the rungholt scene. What could I possibly do wrong that it takes that long as swarmlogic reported like 38 seconds.

Edit: Ok i guess the bad allocation is because the 32bit exe is running into its 2GB limit when started in debug mode from VS2013, so I think this is not a fault of tinyobjloader. I think this issue can be closed, as I do not think there is much that tinyobjloader could do against that :)

**Comment by syoyo** [comment]
Thank you for the report!

I haven't tried 32bit build, but consuming 2GB+ mem is a bit unacceptable situation for 263M of `rungholt.obj`. We should find a way to reduce memory for .obj parsing.

FYI, I got less than ~30 secs to parse rungholt scene on my MacBook Pro 13(64bit build).

**Comment by NoxMortem** [comment]
I have looked into the same problem with tinyobjloader as well as with assimp model loader and I am not really sure if it is really the fault of tinyobjloader .obj parsing, but more the VS2013 debugger who fills up the heap. Once i get it to load with tinyobjloader as well I will report (by editing this post) how long it took, as with assimp the difference was from:

840 seconds release \Ox\Oi started from Visual Studio (F5, which seems to attache a debugger even for a release build) compared to 10 seconds by starting the exe directly out of the build-folder. (For VS users: ctrl+F5 starts the program without attaching a debugger).

Thank you very much for your help, the model loading now works with both libraries!

**Comment by syoyo** [comment]
> F5, which seems to attache a debugger even for a release build

Yes, that's right.  It looks like VS hooks some assertion check or debug facility in MSVC runtime in F5 debug mode even for Release build.

**Comment by NoxMortem** [comment]
btw: Issue can be closed, as it was indeed the requirement to specify the path to the material files.

**Comment by NoxMortem** [comment]
I just tested it again (with attached debugger, debug mode, 32bit) and got the bad alloc exception at 750MB used (3GB memory left) at the exact same position again. I am not sure if it is a stl/debug/tinyobjloader but something definetly is bogus.
