### ISSUE TITLE
No material loaded sponza

### ISSUE THREAD

**Issue by NoxMortem** [syoyo/tinyobjloader#32]
When I try to load the crytek-sponza scene from http://graphics.cs.williams.edu/data/meshes.xml then it seems like no material is loaded.

As the main page wrote:
Feb 06, 2015 : Fix parsing multi-material object

The objects indeed have only 1 material as far as I can tell but assumed the loader can handle multi-material now it should also be able to handle one or none ;)

I expected this to work now:
auto tinyMaterialsN = shapes[i].mesh.material_ids.size();
has the value 3640

std::vector<tinyobj::material_t> materials;
std::string err = tinyobj::LoadObj(shapes, materials, fullpath.c_str());

materials has size == 1 with no name, no texture, nothing.

Each mesh has a different number of material_ids but all values are -1 so this definetly looks like a bug

**Comment by rfoligno** [comment]
You need to specify the material file path in the path mtl_basepath parameter of Load_Obj when the material file is not located in the working folder of the application. As stated in issue #21.

For example

- /WorkingFolder
-- /Materials
--- sponza.mtl
-- /Models
--- sponza.obj
-- Application.exe

``` c++
std::string err = tinyobj::LoadObj(shapes, materials, filename, "materials/");
```

**Comment by NoxMortem** [comment]
This seems to be correct but could you maybe still shed a little bit of light onto the material_ids? If I load the sponza scene and look at the meshes and materials, I get:

    shapes.size() == 381
    materials.size() == 26

Which seems absolutely fine, but what confuses me is:
    
     shapes[i].mesh.material_ids.size()

which varies quite a lot but contains always the same value. The same value likely simply means the mesh has only one value, but how is `shapes[i].mesh.material_ids.size()` determined? One material per face/triangle, this seems to hold fine as indices.size()/3==material_ids.size(). A short yes is absolutely sufficent if I am right, but If I am wrong please enlight me.

**Comment by syoyo** [comment]
```
shapes[i].mesh.material_ids
```

Contains per-face material ID(material_ids.size() == indices.size() / 3).
You can find a material of a face `j` by

```
materials[material_ids[j]]
```

And values in material_ids should not exceed `materials.size() - 1`

**Comment by syoyo** [comment]
And thank you @rfoligno for the help!

**Comment by NoxMortem** [comment]
Thank you for clarification. Issue can be closed.
