### ISSUE TITLE
Normals index buffers

### ISSUE THREAD

**Issue by giordi91** [syoyo/tinyobjloader#39]
Hi, 
I see that you define the shape structure in this way
typedef struct {
  std::vector<float> positions;
  std::vector<float> normals;
  std::vector<float> texcoords;
  std::vector<unsigned int> indices;
  std::vector<int> material_ids; // per-mesh material ID
} mesh_t;

Which only stores the index buffer for vertices, what happen when you have more information per vertex ? for example I get from maya a face definition like this:
f 7/7/13 8/8/14 1/9/15

I assume that the extra information just gets lost?
The problem came up when I notice that using a cube I was getting a normal buffer with 24 normals and of course the index buffer was only using the first 8 elements.

Do you think it might be possible to support those extra information?
For now I am just recomputing the normals and averaging them since I don't need per face per vertex normals.

**Comment by syoyo** [comment]
I see, it would be nice if we have indices for `normals` and `texcoords`.
This would be TODO.

For the time being, If `(shapes[i].mesh.normals.size() / 3) == shapes[i].mesh.indices.size())` then you can assume normals are loaded in facevarying manner(probably most Maya exported .obj works like this)

In such a case, 3 normals(for each triangle vertex) at `j` th face are accessed with 

```
float normals[3][3];

normal[0][0] = shapes[i].mesh.normals[9*j+0]);
normal[0][1] = shapes[i].mesh.normals[9*j+1]);
normal[0][2] = shapes[i].mesh.normals[9*j+2]);

normal[1][0] = shapes[i].mesh.normals[9*j+3]);
normal[1][1] = shapes[i].mesh.normals[9*j+4]);
normal[1][2] = shapes[i].mesh.normals[9*j+5]);

normal[2][0] = shapes[i].mesh.normals[9*j+6]);
normal[2][1] = shapes[i].mesh.normals[9*j+7]);
normal[2][2] = shapes[i].mesh.normals[9*j+8]);
```

**Comment by giordi91** [comment]
Thank you, for now as stated, is not giving any problem, but I can see that giving some trouble is some cases. Like for example if we have uv maps detached from each other (still in the same tile 0-1) but in different "islands". We might need to fix the data structure and duplicate vertexes in order to have that behave properly. Did you ever tried to load those kind of meshes?

M.

**Comment by syoyo** [comment]
> Did you ever tried to load those kind of meshes?

Not yet. Do you have any test dataset so that I can investigate further?

**Comment by syoyo** [comment]
I have added initial support of normal and texcoord indices. You can try it: https://github.com/syoyo/tinyobjloader/tree/normal-texcoord-indices

**Comment by giordi91** [comment]
amazing thank you! I am busy on something else but that s an amazing update man! at least now the user can remap/ reformat data how he wanted! 
Should we close the issue?

**Comment by syoyo** [comment]
Cool. It would be nice closing the issue after you can read/parse normal/texcoord indices correctly.

**Comment by syoyo** [comment]
Its now supported in `master` branch(v1.0.x)
