### ISSUE TITLE
[CRASH] sscanf_s parameters are incorrect

### ISSUE THREAD

**Issue by jpoag** [syoyo/tinyobjloader#41]
There's a crash on MS compilers resulting from a missing buffer size when using sscanf_s.

All 

sscanf_s(token, "%s", namebuf);

should read:

sscanf_s(token, "%s", namebuf, 4096);

Resources:
http://blogs.msdn.com/b/parthas/archive/2006/12/06/application-crash-on-replacing-sscanf-with-sscanf-s.aspx

**Comment by jpoag** [comment]
Fast!

**Comment by syoyo** [comment]
Thanks for pointing out the issue! Now it should be OK on Windows.

**Comment by jpoag** [comment]
It is, thanks!
