### ISSUE TITLE
UTF-8 filepath support

### ISSUE THREAD

**Issue by Kroll** [syoyo/tinyobjloader#42]
If file path have non latin characters (cyrilic in my case) then function LoadObj drops error message "Cannot open file [" << filename << "]" .
Is it possible to add support of UTF-8 encoding for file paths?

**Comment by syoyo** [comment]
Hello Kroll,

It may be possible to support UTF-8 filepath, but I have no idea for the portable way to handle UTF-8 (over Mac/Win/Linux)... Do you have any idea(using C++ STL would be nice)?

**Comment by skurmedel** [comment]
Maybe one could easily add support through C++2011 if the compiler used supports it. Then there is at least partial support.

**Comment by syoyo** [comment]
http://bjoern.hoehrmann.de/utf-8/decoder/dfa/

This looks nice for decoding UTF-8 file path.

@Kroll Please upload a file with UTF-8 name(cyrillic) for testing, or try the above UTF-8 decoder?

**Comment by syoyo** [comment]
Please reopen issue with reproducable test data.
