### ISSUE TITLE
mtl files with both 'd' and 'Tr' set behave unexpectedly

### ISSUE THREAD

**Issue by hamza-tm** [syoyo/tinyobjloader#43]
I've noticed this with many commercial model files, which have materials defined something like:

```
newmtl my_material
        ...	
        d 1.0000
        Tr 0.0000
        ...
```

The loader will first set dissolve to 1, then overwrite it and set it to 0. The result is a material that is fully transparent even though it is intended to be fully visible.

Is it not possible to deal with this? I assume it is a model exporting problem (there really should only be either 'd' or 'Tr' and not both), but it seems to be common.

Thanks

**Comment by syoyo** [comment]
Hello @hamza-tm 

According to the spec http://paulbourke.net/dataformats/mtl/ , there's no `Tr` field. It looks like `Tr` is the extension by some application: http://www.andrewnoske.com/wiki/OBJ_file_format https://en.wikipedia.org/wiki/Wavefront_.obj_file

And current implementation of `tinyobjloader` is doing,

```
    // idissolve
    if ((token[0] == 'd' && isSpace(token[1]))) {
      token += 1;
      material.dissolve = parseFloat(token);
      continue;
    }
    if (token[0] == 'T' && token[1] == 'r' && isSpace(token[2])) {
      token += 2;
      material.dissolve = parseFloat(token);
      continue;
    }
```

Thus dissolve is overwritten by `Tr`. I think this is the expected behaviour. 

But probably I guess value for `Tr` should be parsed in inverted manner, i.e. `dissolve = 1.0 - Tr`.
What is the value of `Tr` when `d = 0`?

**Comment by hamza-tm** [comment]
Thanks, good idea:

I just tested it and found that with `d = 0`, `Tr = 1`.

So yes it seems `Tr` should be parsed in an inverted manner.

**Comment by syoyo** [comment]
Thanks! `Tr` is now inverted.

**Comment by dPavelDev** [comment]
I think it isn't good solution because 3ds Max Wavefront OBJ Exporter v0.94b generate mtl file where Tr = d.

**Comment by syoyo** [comment]
> I think it isn't good solution because 3ds Max Wavefront OBJ Exporter v0.94b generate mtl file where Tr = d.

As I commented earlier, `Tr` is not defined in MTL specification http://paulbourke.net/dataformats/mtl/ , thus there is no correct way of how to interpret `Tr`.

One of possible solution would be introducing a flag whether we invert `Tr` parameter or not when parsing MTL file.

**Comment by dPavelDev** [comment]
> One of possible solution would be introducing a flag whether we invert Tr parameter or not when parsing MTL file.

I think, the best solution would be ignore `Tr` if `d` is declared and show warning when both `Tr` and `d` parameters are declared.

**Comment by syoyo** [comment]
> I think, the best solution would be ignore Tr if d is declared and show warning when both Tr and d parameters are declared.

Good idea!

And I have implemented ignoring `Tr` when `d` exists in this commit:  https://github.com/syoyo/tinyobjloader/commit/7c3206f9193ca259b73fec6556cdcab45c1f5723

This should work well for 3ds max obj exporter(if it exports both `d` and `Tr`)
