### ISSUE TITLE
an empty material is added if .mtl file cannot be read

### ISSUE THREAD

**Issue by jefferis** [syoyo/tinyobjloader#45]
First of all many thanks for sharing this nice library! I have more or less completed a basic wrapper package for R https://github.com/jefferis/readobj.

I have noticed a small bug. If the mtl file cannot be found then an empty material is added. This is because

```c++
std::ifstream matIStream(filepath.c_str());
```
is not checked here https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.cc#L614-L627.

**Comment by syoyo** [comment]
Super cool! > R

We create **default** material when there's no .mtl, so this should be an expected behaviour.
But it may be nice we have `materialFound` flag somewhere?

**Comment by jefferis** [comment]
Thanks for quick response! I think it would be good to indicate that the material file has not been found, but I think you are saying that this should not be an error (because we might want to be able to open an obj file even if the material file is missing).

**Comment by syoyo** [comment]
Okay, I'll consider to add some flag >  I think it would be good to indicate that the material file has not been found

**Comment by jefferis** [comment]
Now in addition, I noticed this because the default material can have some strange values. It seems that 

```c++
InitMaterial(material); 
```
is never called in this case because it is *inside* the read loop (see https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.cc#L421-L462). So should it not be placed write after?

```c++
 material_t material;
```

Finally, I noticed the strange values only from R, not running test_loader, so perhaps different compiler flags are resulting in default initialisation in some cases but not others. I am using `Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)`. Thanks again!

**Comment by syoyo** [comment]
Good catch! > strange values.

Add fix for InitMaterial and add warning message to `err`. Strictly say, its warning, but would be ok to store warning message in `err`, since this does not change any API interface.

https://github.com/syoyo/tinyobjloader/commit/164c152216f75a3d9c1e9b4f367118e9a9343180
