### ISSUE TITLE
material files containing spaces in their name cannot be read

### ISSUE THREAD

**Issue by jefferis** [syoyo/tinyobjloader#46]
I can't seem to decide e.g. from http://www.martinreddy.net/gfx/3d/OBJ.spec if spaces *are* allowed in `.mtl` filenames, but I have some files where this is the case and they cannot be read because:

https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.cc#L784-L792

uses `sscanf` to read a space delimited string.

**Comment by syoyo** [comment]
Hmm... I also don't know white space is allowed in .mtl filename.

Do you have any idea for parsing such a filename? Simply read until newline or '.mtl' found would be suffice?

**Comment by jefferis** [comment]
After reading some more, I found this at http://www.martinreddy.net/gfx/3d/OBJ.spec

```
mtllib filename1 filename2 . . .
```

So it seems that multiple material files can be specified and therefore one cannot just read to the end of the line. The only alternative would be to look for the `.mtl` suffix but there is nothing in the spec that says that files must end in `.mtl` so I think that is not safe either. So the conclusion is that files with spaces in their names must be disallowed.

**Comment by chapulina** [comment]
Hi there! I understand there's a good reason for not supporting spaces directly in MTL filenames. But would you consider some workaround such as encoding or escaping spaces? I would be happy to open a pull request with a proposal in case you're open to it. Thanks!

**Comment by syoyo** [comment]
@chapulina Best way is escape space `\ ` in .obj file. It may be ok(not to break .obj spec) to support quoted filename (`'my file.mtl'` or `"my file.mtl") in mtllib.

**Comment by chapulina** [comment]
Thanks for the suggestion, @syoyo . See a possible implementation on https://github.com/tinyobjloader/tinyobjloader/pull/285.
