### ISSUE TITLE
File not imported correctly

### ISSUE THREAD

**Issue by ibutra** [syoyo/tinyobjloader#47]
Hi,
when importing this [obj](https://gigamove.rz.rwth-aachen.de/d/id/a74akJ8vyueLS6) I get wird results.
First to notice is the indicies count not dividable by 3 for left sphere even though only triangles are present it seems to be capped at 1999. 
The position array contains 1883 values, the obj file contains 546 vertices for this object so that should be 1638 position values shouldn't it?

Im am running arch linux.
Programming in Clion with the included compiler.

**Comment by syoyo** [comment]
Hello. It looks OK to load with the recent version of tinyobjloader in my side(added dummy .mtl file to load .obj correctly).
What is the result with recent master of tinyobjloader?

![screen shot 2015-07-03 at 11 15 15 am](https://cloud.githubusercontent.com/assets/18676/8491494/da4ab99a-2174-11e5-80f3-3f615141651a.png)

```
[LoadOBJ] # of shapes in .obj : 8
  shape[0].name = leftSphere
  shape[0].indices: 3264
  shape[0].vertices: 1884
  shape[0].normals: 1884
  shape[1].name = rightSphere
  shape[1].indices: 3264
  shape[1].vertices: 1884
  shape[1].normals: 1884
  shape[2].name = floor
  shape[2].indices: 6
  shape[2].vertices: 12
  shape[2].normals: 12
  shape[3].name = ceiling
  shape[3].indices: 6
  shape[3].vertices: 12
  shape[3].normals: 12
  shape[4].name = backWall
  shape[4].indices: 6
  shape[4].vertices: 12
  shape[4].normals: 12
  shape[5].name = rightWall
  shape[5].indices: 6
  shape[5].vertices: 12
  shape[5].normals: 12
  shape[6].name = leftWall
  shape[6].indices: 6
  shape[6].vertices: 12
  shape[6].normals: 12
  shape[7].name = light
  shape[7].indices: 6
  shape[7].vertices: 12
  shape[7].normals: 12
```

**Comment by ibutra** [comment]
Hi,

This is embarrassing. 
I am so sorry, I guess I stared too long at it yesterday. It loads fine for me too, I just accessed the wrong pointer. 

Again, sorry for bothering you.

**Comment by syoyo** [comment]
Good now you can load .obj correctly!
