### ISSUE TITLE
Easy fix: double->float conversion warning

### ISSUE THREAD

**Issue by nguillemot** [syoyo/tinyobjloader#50]
I would normally give a pull request, but forking isn't working today for some reason.

`tiny_obj_loader.cc` line 564:

`      material.dissolve = 1.0 - parseFloat(token);`

emits a warning in Visual Studio 2015:

`tiny_obj_loader.cc(564): warning C4244: '=': conversion from 'double' to 'float', possible loss of data`

Fix is simple, just add the suffix `f`:

`      material.dissolve = 1.0f - parseFloat(token);`

**Comment by syoyo** [comment]
Thanks! Fixed!
