### ISSUE TITLE
Empty .obj file

### ISSUE THREAD

**Issue by racarate** [syoyo/tinyobjloader#52]
Should loading an empty .obj file generate an error?

**Comment by syoyo** [comment]
Absolutely yes.

**Comment by racarate** [comment]
Ah, ok.  I think I had an .obj file with only the name of a material in it and no other lines -- no error was generated, but accessing shapes[0].mesh.positions.size() caused a crash.  Is that correct?

**Comment by syoyo** [comment]
Why not first check shapes.size()?

**Comment by racarate** [comment]
Ah, I see -- so an error is generated only for a completely empty .obj file but as long as there are some characters in the file we still need to manually check.

**Comment by syoyo** [comment]
When .obj contains no triangles but lines, `shapes` will be zero and this would be expected behavior(adding support for parsing lines or other primitives are todo).
