### ISSUE TITLE
map_Ns interpreted wrong; bump map support missing

### ISSUE THREAD

**Issue by marlam** [syoyo/tinyobjloader#53]
The map_Ns directive in an MTL file specifies a map for the shininess parameter (aka specular exponent). See https://en.wikipedia.org/wiki/Wavefront_.obj_file#Texture_maps and http://www.fileformat.info/format/material/.

However, tinyobjloader stores it in material_t.normal_texname, indicating that it stores a normal map.
This is confusing.

As far as I know, OBJ does not actually support "real" normal maps, only the simpler variant of bump maps, using the "map_bump" or "bump" directive. Tinyobjloader does not currently support bump maps; it would be nice to have material_t.bump_texname for that purpose.

**Comment by syoyo** [comment]
Thanks! Now `map_Ns` is interpreted as specular highlight map. And adds support for bump, displacement and alpha texture.

**Comment by marlam** [comment]
Thank you very much! This has got to be the fastest bug fix / feature enhancement ever :)

There is a small bug in the patch, though: you assign map_d to `material.bump_texname` instead of `material.alpha_texname`.

Still, with that fixed, I can now render Crytek Sponza from http://graphics.cs.williams.edu/data/meshes.xml with bump maps and mask textures (after a few fixes to their .mtl file). Very nice!

**Comment by syoyo** [comment]
> map_d to material.bump_texname

Good cactch. Fixed in recent master.
