### ISSUE TITLE
No longer able to build python module

### ISSUE THREAD

**Issue by chrisliebert** [syoyo/tinyobjloader#54]
Previously I was able to build the tinyobjloader module for Python however in the latest version of master branch I am having trouble on Windows and Linux.

This is the last commit (Aug 8, 2015) I was able to build for python 3 with compile warnings (python2 build failed):
https://github.com/syoyo/tinyobjloader/tree/d299576eac0b6400873b291fa496bf5ef876a206

## Output on latest ##
(available at https://github.com/syoyo/tinyobjloader /tree/475bc83ef3193198f145896abc864429ef07fdbf)

## Ubuntu Linux with Python 3.4.3: ##
python3 setup.py build
running build
running build_ext
building 'tinyobjloader' extension
creating build
creating build/temp.linux-x86_64-3.4
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c main.cpp -o build/temp.linux-x86_64-3.4/main.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
main.cpp: In function ‘PyObject* pyLoadObj(PyObject*, PyObject*)’:
main.cpp:66:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "positions";
                              ^
main.cpp:69:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "normals";
                              ^
main.cpp:72:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "texcoords";
                              ^
main.cpp:75:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "indicies";
                              ^
main.cpp:78:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "material_ids";
                              ^
main.cpp:108:84: error: ‘struct tinyobj::material_t’ has no member named ‘normal_texname’
         PyDict_SetItemString(matobj, "normal_texname", PyUnicode_FromString((*mat).normal_texname.c_str()));
                                                                                    ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

## Output for python 2.7: ##
python setup.py build
running build
running build_ext
building 'tinyobjloader' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c main.cpp -o build/temp.linux-x86_64-2.7/main.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
main.cpp: In function ‘PyObject* pyLoadObj(PyObject*, PyObject*)’:
main.cpp:66:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "positions";
                              ^
main.cpp:69:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "normals";
                              ^
main.cpp:72:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "texcoords";
                              ^
main.cpp:75:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "indicies";
                              ^
main.cpp:78:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
                 current_name = "material_ids";
                              ^
main.cpp:108:84: error: ‘struct tinyobj::material_t’ has no member named ‘normal_texname’
         PyDict_SetItemString(matobj, "normal_texname", PyUnicode_FromString((*mat).normal_texname.c_str()));
                                                                                    ^
main.cpp: At global scope:
main.cpp:133:27: error: variable ‘PyModuleDef moduledef’ has initializer but incomplete type
 static struct PyModuleDef moduledef = {
                           ^
main.cpp:134:5: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
     PyModuleDef_HEAD_INIT,
     ^
main.cpp: In function ‘void PyInit_tinyobjloader()’:
main.cpp:145:38: error: ‘PyModule_Create’ was not declared in this scope
     return PyModule_Create(&moduledef);
                                      ^
main.cpp:145:38: error: return-statement with a value, in function returning 'void' [-fpermissive]
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by syoyo** [comment]
You can contribute a patch.

**Comment by chrisliebert** [comment]
It appears that "normal_texname" was replaced by "specular_highlight_texname". I was able to build with python 3 by replacing 
```
PyDict_SetItemString(matobj, "normal_texname", PyUnicode_FromString((*mat).normal_texname.c_str()));
```
in main.cpp line 108 with
```
PyDict_SetItemString(matobj, "specular_highlight_texname", PyUnicode_FromString((*mat).specular_highlight_texname.c_str()));
```
string deprecation warnings fixed by changing current_name to std::string instead of char*. and using .c_str().

Here is a full source for python/main.cpp working for Python 3 on Windows/Linux:
```
//python3 module for tinyobjloader
//
//usage:
// import tinyobjloader as tol
// model = tol.LoadObj(name)
// print(model["shapes"])
// print(model["materials"]

#include <Python.h>
#include <vector>
#include "../tiny_obj_loader.h"

typedef std::vector<double> vectd;

PyObject*
pyTupleFromfloat3 (float array[3])
{
    int i;
    PyObject* tuple = PyTuple_New(3);

    for(i=0; i<=2 ; i++){
        PyTuple_SetItem(tuple, i, PyFloat_FromDouble(array[i]));
    }

    return tuple;
}

extern "C"
{

static PyObject*
pyLoadObj(PyObject* self, PyObject* args)
{
    PyObject *rtndict, *pyshapes, *pymaterials, 
             *current, *meshobj;

    char const* filename;
    std::string current_name;
    vectd vect;

    std::vector<tinyobj::shape_t> shapes;
    std::vector<tinyobj::material_t> materials;

    if(!PyArg_ParseTuple(args, "s", &filename))
        return NULL;

    tinyobj::LoadObj(shapes, materials, filename);

    pyshapes = PyDict_New();
    pymaterials = PyDict_New();
    rtndict = PyDict_New();

    for (std::vector<tinyobj::shape_t>::iterator shape = shapes.begin() ;
         shape != shapes.end(); shape++)
    {
         meshobj = PyDict_New();
         tinyobj::mesh_t cm  = (*shape).mesh;

         for (int i = 0; i <= 4; i++ )
         {
            current = PyList_New(0);

           switch(i) {

           case 0: 
                current_name = "positions";
                vect = vectd(cm.positions.begin(), cm.positions.end()); break;
           case 1:
                current_name = "normals";
                vect = vectd(cm.normals.begin(), cm.normals.end()); break;
           case 2:
                current_name = "texcoords";
                vect = vectd(cm.texcoords.begin(), cm.texcoords.end()); break;
           case 3:
                current_name = "indicies";
                vect = vectd(cm.indices.begin(), cm.indices.end()); break;
           case 4:
                current_name = "material_ids";
                vect = vectd(cm.material_ids.begin(), cm.material_ids.end()); break;
            
            }
           
           for (vectd::iterator it = vect.begin() ;
                it != vect.end(); it++)
            {
                PyList_Insert(current, it - vect.begin(), PyFloat_FromDouble(*it));
            }

            PyDict_SetItemString(meshobj, current_name.c_str(), current);
            
         }

         PyDict_SetItemString(pyshapes, (*shape).name.c_str(), meshobj);
    }

    for (std::vector<tinyobj::material_t>::iterator mat = materials.begin() ;
         mat != materials.end(); mat++)
    {
        PyObject *matobj = PyDict_New();

        PyDict_SetItemString(matobj, "shininess",  PyFloat_FromDouble((*mat).shininess));
        PyDict_SetItemString(matobj, "ior",  PyFloat_FromDouble((*mat).ior));
        PyDict_SetItemString(matobj, "dissolve",  PyFloat_FromDouble((*mat).dissolve));
        PyDict_SetItemString(matobj, "illum",  PyLong_FromLong((*mat).illum));
        PyDict_SetItemString(matobj, "ambient_texname", PyUnicode_FromString((*mat).ambient_texname.c_str()));
        PyDict_SetItemString(matobj, "diffuse_texname", PyUnicode_FromString((*mat).diffuse_texname.c_str()));
        PyDict_SetItemString(matobj, "specular_texname", PyUnicode_FromString((*mat).specular_texname.c_str()));
        PyDict_SetItemString(matobj, "specular_highlight_texname", PyUnicode_FromString((*mat).specular_highlight_texname.c_str()));
        PyDict_SetItemString(matobj, "ambient", pyTupleFromfloat3((*mat).ambient));
        PyDict_SetItemString(matobj, "diffuse", pyTupleFromfloat3((*mat).diffuse));
        PyDict_SetItemString(matobj, "specular", pyTupleFromfloat3((*mat).specular));
        PyDict_SetItemString(matobj, "transmittance", pyTupleFromfloat3((*mat).transmittance));
        PyDict_SetItemString(matobj, "emission", pyTupleFromfloat3((*mat).emission));

        PyDict_SetItemString(pymaterials, (*mat).name.c_str(), matobj);
    }

    PyDict_SetItemString(rtndict, "shapes", pyshapes);
    PyDict_SetItemString(rtndict, "materials", pymaterials);

    return rtndict;
}


static PyMethodDef mMethods[] = {

{"LoadObj", pyLoadObj, METH_VARARGS},
{NULL, NULL, 0, NULL}

};


static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "tinyobjloader",
    NULL,
    -1,
    mMethods
};


PyMODINIT_FUNC
PyInit_tinyobjloader(void)
{
    return PyModule_Create(&moduledef);
}

}
```

**Comment by syoyo** [comment]
"normal_texname" is not a wavefront .mtl specification as pointed by this issue https://github.com/syoyo/tinyobjloader/issues/53, so I removed it.

> Here is a full source for python/main.cpp working for Python 3 on Windows/Linux:

Could you please make it as PR?

**Comment by chrisliebert** [comment]
Applied patch to python/main.cpp in https://github.com/chrisliebert/tinyobjloader.git (Unable to create branch / pull request due to error 403 access denied)

**Comment by syoyo** [comment]
You may need to learn github. PR should be possible.
