### ISSUE TITLE
adding invalid/unused material id (-1) to meshes' materials_ids vector

### ISSUE THREAD

**Issue by pboechat** [syoyo/tinyobjloader#56]
Simply add a

if (material_id != -1)

@tiny_obj_loader.cc:406

Thanks

**Comment by syoyo** [comment]
mesh.materials_ids.size() should have same size of mesh.indices.size()/3, thus doing that won't work.

**Comment by pboechat** [comment]
ok, but just out of curiosity: why do you need to a material id per index?

**Comment by syoyo** [comment]
For correctly represent per-face material.

**Comment by pboechat** [comment]
it looks like an overkill. couldn't you simply assign multiple materials per shape/face/group?
