### ISSUE TITLE
NULL material path causes warning on LoadObj

### ISSUE THREAD

**Issue by redagito** [syoyo/tinyobjloader#58]
When calling LoadObj without an material base path, the function returns an non-empty error string
> WARN: Material file [ sphere.mtl ] not found. Created a default material..

According to the documentation 

> /// Returns empty string when loading .obj success.

This should not happen, also I am using size() != 0 of the return string as error checking mechanism which fails in this case where I just want to load the mesh without the material data.

**Comment by syoyo** [comment]
Yes, its a good point. Current API design & error/warn handling is a bit inconsistent. 

I am considering to re-design API something like

```
std::string warn;
std::string err;
int retcode = LoadObj(..., warn, err);
if (retcode < 0) { // err
   printf("err = %s\n", err.c_str();
}

if (!warn.empty()) {
  printf("warn: %s\n", warn.c_str());
}
```

Is this looks nice?

**Comment by redagito** [comment]
Separate strings for error and warning seems overkill
`bool LoadObj(..., std::string& ret);
`...
`std::string ret;
`if (!LoadObj(..., ret)) {
` // Error handling
`}
`if (!ret.empty()) {
` // Warning handling
`}

**Comment by redagito** [comment]
Update: Loading OBJ files seems to fail completely when there is no corresponding MTL file.
LoadObj returns warning and shapes is empty after the call. This used to work with a previous version
> https://github.com/syoyo/tinyobjloader/tree/ba5fde9fd59ce9b36b492ad6c6cfd4c82749d763

**Comment by syoyo** [comment]
Improved API. And I think this issue was fixed also > Loading OBJ files seems to fail completely
