### ISSUE TITLE
The problem when loading texture coordinate 

### ISSUE THREAD

**Issue by vinthony** [syoyo/tinyobjloader#59]
HI,
Thanks for your project, but there is a wired problem when i using the branch `normal-texcoord-indices`,I want to get the normal indices and texcoord information into my program,but when i debugging, all the indices(normal,texture,position) are the same. I don't think it's the right answer of the obj file. is there anything wrong with my understand?

**Comment by vinthony** [comment]
I read the code of this part and find you are using  `cache` to build these index, so it's my fault. anyway, i don't think separated the (x,y,z) positions or normals or texture coordinates into continuous array is a good way to program. why not using array or some other data structure to make it easier to use?

**Comment by syoyo** [comment]
You can re-organize your own data structure from tinyobjloader's facevarying attribute format.

**Comment by skurmedel** [comment]
Tying them together has problems on its own too. 

Say you were to tie position, normal and UV together, that gives a struct of roughly 64 bytes.

If you only need **one** attribute (example: manipulating the normals) for some processing and need to loop over a gigantic mesh, you'll pull in an additional ~48 bytes for each item into memory cache. That's going to affect your cache hits. It only gets worse the more stuff you put in your struct.

I think a better idea in that case would be to have tinyobjloader provide a callback for each read attribute and let you build your own structure that way. But that complicates the API a lot.

**Comment by skurmedel** [comment]
Sorry obviously meant 32 bytes, lol. Updated my comment.

**Comment by giordi91** [comment]
I guess it depends on what the user want to do? Usually for real-time rendering we interleave the data, postion normal uv etc, but on the cpu side probably if you need to manipulate your data you might want flat buffers of separated data. Not sure if there is a silver bullet for that

**Comment by syoyo** [comment]
Yeah, no silver bullet exists.

tinyobjloader is desgined for portable(single-file), and moderate processing time and moderate memory consumption. If you want fast and memory efficient solution such like realtime rendering purpose, you are better first try other .obj loader such like assimp.

> I think a better idea in that case would be to have tinyobjloader provide a callback for each read attribute 

Anyway, callback API seem an interesting option(as .ply loader does http://people.cs.kuleuven.be/~ares.lagae/libply/), and I think it won't API much complex. PR is welcome :-)

**Comment by syoyo** [comment]
FYI, I have added callback API in `develop` branch: https://github.com/syoyo/tinyobjloader/tree/develop/examples/callback_api

Also, `develop` branch supports having different vertex index for position, normal and texcoords, so this version should solve the issue.

PR and feedback on API design are welcome.

**Comment by syoyo** [comment]
> all the indices(normal,texture,position) are the same

Now `master`(v1.0.x) has different indices for position, normal and texcoord.
