### ISSUE TITLE
"err" is missing in README.md

### ISSUE THREAD

**Issue by Hyunan-Kwon** [syoyo/tinyobjloader#60]
Please, add "err" at README.md:90.
> ~~bool ret = tinyobj::LoadObj(shapes, materials, inputfile.c_str());~~
> bool ret = tinyobj::LoadObj(shapes, materials, **err,** inputfile.c_str());

Thanks!

**Comment by Hyunan-Kwon** [comment]
And, is it right that map_Ns means "specular highlight map"?

At README.md:136,
> ~~printf("  material.map_Ns = %s\n", materials[i].normal_texname.c_str());~~
> printf("  material.map_Ns = %s\n", materials[i].**specular_hightlight_texname**.c_str());

**Comment by syoyo** [comment]
Thanks! Fixed!
