### ISSUE TITLE
How to load obj as non-grouped?

### ISSUE THREAD

**Issue by acterhd** [syoyo/tinyobjloader#69]
Hello, I have problems with single load OBJ. Need load obj without partition. But with it I have problems. I not found in internet how unify OBJ. I have no enough memory build octree per every group, so need load obj as one part.

**Comment by syoyo** [comment]
Currently there's no such a feature in tinyobjloader.

We may doable to create non-grouped mesh using custom parsing function callback, but for a while you need to create non-grouped .obj in modeler/exporter level.

**Comment by syoyo** [comment]
You can now use callback AP and design your own data structure(i.e. load meshes without grouping)I in `develop` branch https://github.com/syoyo/tinyobjloader/tree/develop/examples/callback_api

**Comment by syoyo** [comment]
`develop` is now merged into `master` and you can use callback API by default. This should solve your problem.
