### ISSUE TITLE
Uninitialized member warning

### ISSUE THREAD

**Issue by redagito** [syoyo/tinyobjloader#70]
While building the library, the compiler reports several uninitialized variables in 
> struct vertex_index
in file tiny_obj_loader.h

The members 
> int v_idx, vt_idx, vn_idx;
are not initilaized by the default constructor 
> vertex_index() {}
which might lead to undefined behaviour.

Can those members be set to some kind of "uninitialized" value (-1 maybe)?
I did not look into the usage of the struct. If this case is already covered by other code, then please add default values to silence this warning.

Compiler warnings are
> Member 'v_idx' was not initialized in this constructor
> Member 'vn_idx' was not initialized in this constructor
> Member 'vt_idx' was not initialized in this constructor

**Comment by syoyo** [comment]
Thanks! Use `-1` as default value.
(Add check `-1` when using vertex_index will be done in another commit).
