### ISSUE TITLE
Problem with some OBJs with shared UV coords

### ISSUE THREAD

**Issue by Kthulhu** [syoyo/tinyobjloader#73]
This OBJ file: http://ow.ly/4mHMap (simple cube model from Maya - 8 pts, 6 faces, 14 uv coords)causes that: http://ow.ly/4mIdkx
"i" is one of the points that already cached, just with difference uv ref, since it's interconnected mesh/faces. As you can see, vertexCache _already_ has 8 points in it, and this is going to be 9th, since std::map thinks they're differs. Which is obviously incorrect.

Upon loading this file there's 42 elements in mesh.positions, yielding 14 points instead of 8.
The reason is that code(line ~450, i reformatted the header):

static unsigned int updateVertex(std::map<vertex_index, unsigned int> &vertexCache, std::vector<float> &positions, std::vector<float> &normals, std::vector<float> &texcoords, const std::vector<float> &in_positions, const std::vector<float> &in_normals, const std::vector<float> &in_texcoords, const vertex_index &i)
{
	const std::map<vertex_index, unsigned int>::iterator it = vertexCache.find(i);
	if(it != vertexCache.end()) { return it->second; }	// return vtx number if yes

Produces redundant points in mesh.positions when one of the points with the idx that already was cached, using different texture coord(for different face).
I'm afraid that proper change(with compacted UVs/references to them) will require massive rewrite of the lib.

**Comment by syoyo** [comment]
Current design&implementation of tinyobjloader cannot handle such a data.

To support more various .obj data, I have decided to start refactoring&introducing new design of tinyobjloader in `develop` branch.

https://github.com/syoyo/tinyobjloader/tree/develop

```

**Comment by syoyo** [comment]
`develop` is now merged into `master`. Thus your problem should be solved in this new version.
