### ISSUE TITLE
Hope the viewer will be fulfilled with textures shown :)

### ISSUE THREAD

**Issue by JobsSteve** [syoyo/tinyobjloader#74]

**Comment by skurmedel** [comment]
Do you mean you would want textures to be rendered in the .obj-viewer? Sorry, a bit hard to read the title as it is :)

**Comment by syoyo** [comment]
Yes, @JobsSteve you should describe details. And PR are always welcome.

FYI, I am working new&improved version in `develop` branch, and there's now OpenGL viewer example there: https://github.com/syoyo/tinyobjloader/tree/develop/examples/viewer

**Comment by KammutierSpule** [comment]
I vote for a Material use / implementation on the viewer.

**Comment by JobsSteve** [comment]
@skurmedel  @syoyo  Yes, that's exactly what I mean. Sorry for my not good in English ;)

**Comment by skurmedel** [comment]
@JobsSteve No problem :) Not native speaker myself.
@syoyo @JobsSteve I could volunteer to add support but... what formats would be good to support? The problem arises with dependencies. I've used [stb_image.h](https://github.com/nothings/stb/blob/master/stb_image.h) in my own stuff, its very lightweight but it only supports the common formats. I guess one could use your exr-library for .exrs, but I don't think .exrs are very common as textures outside big hollywood studios, or are they?

**Comment by syoyo** [comment]
Cool! > I could volunteer to add support

I am using stb and tinyexr to load textures(jpg,png,exr) for our various applications(non-VFX),  so EXR should be a quite common format.

**Comment by skurmedel** [comment]
Is this still relevant? I was working on this, but then put it to rest for a while. Now that tinyobjloader works quite differently I'll probably have redo it.

**Comment by syoyo** [comment]
No one is working on this, thus your PR is welcome.

API and data structure has been changed from v1.0, please see viewer example code https://github.com/syoyo/tinyobjloader/blob/master/examples/viewer/viewer.cc for details.

**Comment by chrisliebert** [comment]
https://github.com/syoyo/tinyobjloader/pull/103

**Comment by syoyo** [comment]
Merged PR so closing the issue.
