### ISSUE TITLE
ifstream::getline doesn't handle non-native lf-cr-and-crlf

### ISSUE THREAD

**Issue by erwincoumans** [syoyo/tinyobjloader#81]
tinyobjloader uses ifstream::getline, which fails to handle files with different line endings, for example copied from a different operating system. The filename (mtl file or texture file) can have a \r appended, and the file fails to load.

See discussion here:
See http://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf

I fixed it in my Bullet fork using the stackoverflow solution:
See https://github.com/bulletphysics/bullet3/blob/master/examples/ThirdPartyLibs/Wavefront/tiny_obj_loader.cpp#L33

**Comment by syoyo** [comment]
Thanks! Now fixed.
