### ISSUE TITLE
‘struct tinyobj::attrib_t’ has no member named ‘positions’

### ISSUE THREAD

**Issue by sebbekarlsson** [syoyo/tinyobjloader#84]
src/App.cpp: In member function ‘void App::draw(float)’:
src/App.cpp:266:35: error: ‘struct tinyobj::attrib_t’ has no member named ‘positions’
                 float vx = attrib.positions[3*idx.vertex_index+0];

**Comment by syoyo** [comment]
You are probably posting to wrong project.

There is no `src/App.cpp` file in this repo.  And `attrib.vertices`, not `attrib.positions`

**Comment by sebbekarlsson** [comment]
In your example code you used "attrib.positions" (in the readme file)... I went through your source code and found out by myself that it should have been "attrib.vertices".

Note: this was on the develop branch!

**Comment by syoyo** [comment]
> In your example code you used "attrib.positions" (in the readme file)... I went through your source code and found out by myself that it should have been "attrib.vertices".
> 
> Note: this was on the develop branch!

You should describe these information when you post the issue. And inconsistency in README has been fixed already: https://github.com/syoyo/tinyobjloader/commit/b8c33156de96592903f06acc619ac921adc251c3
