### ISSUE TITLE
Texture options are missing

### ISSUE THREAD

**Issue by hydraskillz** [syoyo/tinyobjloader#85]
No support for texture options. If options are present, they are read in as part of the texture path.

**Comment by syoyo** [comment]
PR are always welcome.

**Comment by syoyo** [comment]
Added initial support of parsing texture options in `texopt` branch : https://github.com/syoyo/tinyobjloader/tree/texopt

@hydraskillz You can contribute writing more tests and implementatons.

**Comment by syoyo** [comment]
Adde texture options support in this commit: https://github.com/syoyo/tinyobjloader/commit/0948ca0417455dd82891547699e97ba142021a7b
