### ISSUE TITLE
LoadObjWithCallback() Triangulation

### ISSUE THREAD

**Issue by adishavit** [syoyo/tinyobjloader#87]
Does `LoadObjWithCallback()` triangulate non-triangles?
If it doesn't, then how can the app know how many vertices are in the face, since _each_ index generates an _independent_ callback?
OTOH, the function header documentation mentions: 
`/// 'triangulate' is optional, and used whether triangulate polygon face in .obj or not.` 
but the function does not have this argument at all!
There seems to be some inconsistency here.

**Comment by syoyo** [comment]
Thanks for pointing out.

1. Commend was wrong. Removed.
2. I've fixed calling `index_cb` per `f` line.

Now callback API just pass parsed `f` line to `index_cb` as is, so the user application need to triangulate if necessary.

I guess this solves your question.

**Comment by adishavit** [comment]
Great 👍 
Thanks!
