### ISSUE TITLE
OBJ texture coordinates can have 3 elements

### ISSUE THREAD

**Issue by adishavit** [syoyo/tinyobjloader#88]
According to the OBJ specification, the `vt` element may have up to 3 elements. 
If the 3rd is missing it defaults to 0.
The current callback API only returns 2 coordinates: `void (*texcoord_cb)(void *user_data, float x, float y);`

**Comment by syoyo** [comment]
Ah, I see.

Also, according to the .obj spec, vertex coordinates can have `w` element(default = 1). So I have added support for these.

**Comment by adishavit** [comment]
Thanks!
(ref: [commit](https://github.com/syoyo/tinyobjloader/commit/75e64cd47a1217f4200bfcb2c65c5c1ccc196dbf))
