### ISSUE TITLE
Populate array buffer with data in  attrib_t directly?

### ISSUE THREAD

**Issue by peanutandchestnut** [syoyo/tinyobjloader#98]
Hi

I found that in order to populate array buffer, all examples make a copy of every position, normal, etc to  create a new vertex. 
I was wondering if there is a way to avoid it,  so we can populate array buffer directly from attrib_t? Current attrib_t contains all information for all the shapes, i have no luck in finding the boundary between shapes.

By the way, I'm new to opengl and tinyobjloader and .obj file.

**Comment by syoyo** [comment]
1. tinyobjloader is not designed for OpenGL.
2. You can use callback API to load .obj data fit into your data structure

**Comment by peanutandchestnut** [comment]
Callback should work. 
Thanks for the help.

**Comment by syoyo** [comment]
Callback API is the best solution for you, but there would be another solution: https://github.com/syoyo/tinyobjloader/blob/master/experimental/tinyobj_loader_opt.h

This is much more OpenGL friendly. Although I haven't tested yet, you may send `attrib_t` data to VertexBuffer directly, then pass `shape_t::face_offset` and `shape_t::length` to `glDrawArrays`(Assume you read .obj data with triangulation) to render each shape.
