### ISSUE TITLE
Support for Java?

### ISSUE THREAD

**Issue by acterhd** [syoyo/tinyobjloader#99]
Hello. Will support for Java platforms? In Java very need obj loader...

**Comment by syoyo** [comment]
You can write JNI binding. PR welcome.

**Comment by chrisliebert** [comment]
It is also possible to use SWIG to generate the wrapper/bindings for you. For example, add the following file called tiny_obj_wrapper.i and place in the tinyobjloader directory:

`
/* tiny_obj_wrapper.i */
#ifdef SWIG

 %module tiny_obj_wrapper

 %{
  #include "tiny_obj_wrapper.i"
 %}

 %include "tiny_obj_loader.h"

#endif /* SWIG */
`

Now run `swig -java -cxx tiny_obj_wrapper.i` and it will generate a bunch of Java classes along with a C++ file which is needed to build a shared library.
You could also try just running `swig -java tiny_obj_wrapper.i` which would provide a pure C version.  It is also possible to have CMake run SWIG and build shared library. See http://www.swig.org/Doc1.3/Introduction.html.

**Comment by chrisliebert** [comment]
[Example CMakeLists.txt for SWIG](https://github.com/chrisliebert/quick-3d/blob/master/ffi/Java/wrapper/CMakeLists.txt)

**Comment by syoyo** [comment]
Cool! > SWIG

**Comment by acterhd** [comment]
My project in Java at this moment died... :( 
Still alive only C++ version of Path Tracing.
